var songs = [
  {title: 'DREADLOCK HOLIDAY', author: '10CC', lang: 'EN'},
  {title: 'CHANGES', author: '2PAC', lang: 'EN'},
  {title: 'TAKE ON ME', author: 'A-HA', lang: 'EN'},
  {title: 'DANCING QUEEN', author: 'ABBA', lang: 'EN'},
  {title: 'GIMME! GIMME! GIMME!', author: 'ABBA', lang: 'EN'},
  {title: 'MAMMA MIA', author: 'ABBA', lang: 'EN'},
  {title: 'BACK IN BLACK', author: 'AC/DC', lang: 'EN'},
  {title: 'HIGHWAY TO HELL', author: 'AC/DC', lang: 'EN'},
  {title: 'ALL THAT SHE WANTS', author: 'ACE OF BASE', lang: 'EN'},
  {title: 'ROLLING IN THE DEEP', author: 'ADELE', lang: 'EN'},
  {title: 'SKYFALL', author: 'ADELE', lang: 'EN'},
  {title: 'SOMEONE LIKE YOU', author: 'ADELE', lang: 'EN'},
  {title: 'ADIEMUS', author: 'ADIEMUS', lang: '-'},
  {title: 'DREAM ON', author: 'AEROSMITH', lang: 'EN'},
  {title: 'I DON\'T WANT TO MISS A THING', author: 'AEROSMITH', lang: 'EN'},
  {title: 'IRONIC', author: 'ALANIS MORRISSETTE', lang: 'EN'},
  {title: 'KEELHAULED', author: 'ALESTORM', lang: 'EN'},
  {title: 'FOREVER YOUNG', author: 'ALPHAVILLE', lang: 'EN'},
  {title: 'BREEZEBLOCKS', author: 'ALT-J', lang: 'EN'},
  {title: 'ENIGMA (GIVE A BIT OF MMM TO ME)', author: 'AMANDA LEAR', lang: 'EN'},
  {title: 'A HORSE WITH NO NAME', author: 'AMERICA', lang: 'EN'},
  {title: 'THIS IS THE LIVE', author: 'AMY MACDONALD', lang: 'EN'},
  {title: 'REHAB', author: 'AMY WINEHOUSE', lang: 'EN'},
  {title: 'TIME TO SAY GOODBYE', author: 'ANDREA BOCELLI, SARAH BRIGHTMAN', lang: 'EN'},
  {title: 'FOUR SEASONS, SPRING', author: 'ANTIONIO VIVALDI', lang: '-'},
  {title: 'CANCION DEL MARIACHI', author: 'ANTONIO BANDERAS, LOS LOBOS', lang: 'ES'},
  {title: 'BARBIE GIRL', author: 'AQUA', lang: 'EN'},
  {title: 'AGAIN', author: 'ARCHIVE', lang: 'EN'},
  {title: 'DO I WANNA KNOW?', author: 'ARCTIC MONKEYS', lang: 'EN'},
  {title: 'RESPECT', author: 'ARETHA FRANKLIN', lang: 'EN'},
  {title: 'THINK', author: 'ARETHA FRANKLIN', lang: 'EN'},
  {title: 'HEY BROTHER', author: 'AVICII', lang: 'EN'},
  {title: 'WAKE ME UP', author: 'AVICII', lang: 'EN'},
  {title: 'EVERYBODY', author: 'BACKSTREET BOYS', lang: 'EN'},
  {title: 'WHO LET THE DOGS OUT', author: 'BAHA MEN', lang: 'EN'},
  {title: 'WOMAN IN LOVE', author: 'BARBRA STREISAND', lang: 'EN'},
  {title: 'GOOD VIBRATIONS', author: 'BEACH BOYS', lang: 'EN'},
  {title: 'I GET AROUND', author: 'BEACH BOYS', lang: 'EN'},
  {title: 'HOW DEEP IS YOUR LOVE', author: 'BEE GEES', lang: 'EN'},
  {title: 'STAYIN\' ALIVE', author: 'BEE GEES', lang: 'EN'},
  {title: 'STAND BY ME', author: 'BEN E. KING', lang: 'EN'},
  {title: 'HALO', author: 'BEYONCÉ', lang: 'EN'},
  {title: 'ROCK AROUND THE CLOCK', author: 'BILL HALEY', lang: 'EN'},
  {title: 'HOOKED ON A FEELING', author: 'BJÖRN SKIFS', lang: 'EN'},
  {title: 'I GOTTA FEELING', author: 'BLACK EYED PEAS', lang: 'EN'},
  {title: 'WHERE IS THE LOVE?', author: 'BLACK EYED PEAS', lang: 'EN'},
  {title: 'IRON MAN', author: 'BLACK SABBATH', lang: 'EN'},
  {title: 'PARANOID', author: 'BLACK SABBATH', lang: 'EN'},
  {title: 'ALL THE SMALL THINGS', author: 'BLINK-182', lang: 'EN'},
  {title: 'CALL ME', author: 'BLONDIE', lang: 'EN'},
  {title: 'MARIA', author: 'BLONDIE', lang: 'EN'},
  {title: 'SONG 2', author: 'BLUR', lang: 'EN'},
  {title: 'BLOWIN\' IN THE WIND', author: 'BOB DYLAN', lang: 'EN'},
  {title: 'KNOCKIN\' ON HEAVEN\'S DOOR', author: 'BOB DYLAN', lang: 'EN'},
  {title: 'LIKE A ROLLING STONE', author: 'BOB DYLAN', lang: 'EN'},
  {title: 'I SHOT THE SHERIFF', author: 'BOB MARLEY', lang: 'EN'},
  {title: 'NO WOMAN NO CRY', author: 'BOB MARLEY', lang: 'EN'},
  {title: 'DON\'T WORRY BE HAPPY', author: 'BOBBY MCFERRIN', lang: 'EN'},
  {title: 'IT\'S MY LIFE', author: 'BON JOVI', lang: 'EN'},
  {title: 'LIVIN\' ON A PRAYER', author: 'BON JOVI', lang: 'EN'},
  {title: 'DADDY COOL', author: 'BONEY M', lang: 'EN'},
  {title: 'RASPUTIN', author: 'BONEY M', lang: 'EN'},
  {title: 'HOLDING OUT FOR A HERO', author: 'BOONIE TYLER', lang: 'EN'},
  {title: 'TOTAL ECLIPSE OF THE HEART', author: 'BOONIE TYLER', lang: 'EN'},
  {title: 'MORE THAN A FEELING', author: 'BOSTON', lang: 'EN'},
  {title: 'MAYBE', author: 'BRAINSTORM', lang: 'EN'},
  {title: '... BABY ONE MORE TIME', author: 'BRITNEY SPEARS', lang: 'EN'},
  {title: 'OOPS!... I DID IT AGAIN', author: 'BRITNEY SPEARS', lang: 'EN'},
  {title: 'TOXIC', author: 'BRITNEY SPEARS', lang: 'EN'},
  {title: 'BORN IN THE U.S.A.', author: 'BRUCE SPRINGSTEEN', lang: 'EN'},
  {title: 'CALL ME MAYBE', author: 'CARLY RAE JEPSEN', lang: 'EN'},
  {title: 'MY HEART WILL GO ON', author: 'CELINE DION', lang: 'EN'},
  {title: 'BELIEVE', author: 'CHER', lang: 'EN'},
  {title: 'THE SHOOP SHOOP SONG', author: 'CHER', lang: 'EN'},
  {title: 'LET\'S TWIST AGAIN', author: 'CHUBBY CHECKER', lang: 'EN'},
  {title: 'JOHNNY B. GOOD', author: 'CHUCK BERRY', lang: 'EN'},
  {title: 'HYMN FOR THE WEEKEND', author: 'COLDPLAY', lang: 'EN'},
  {title: 'VIVA LA VIDA', author: 'COLDPLAY', lang: 'EN'},
  {title: 'SUNSHINE OF YOUR LOVE', author: 'CREAM', lang: 'EN'},
  {title: 'FORTUNATE SON', author: 'CREEDENCE CLEARWATER REVIVAL', lang: 'EN'},
  {title: 'HAVE YOU EVER SEEN THE RAIN?', author: 'CREEDENCE CLEARWATER REVIVAL', lang: 'EN'},
  {title: 'DO YOU REALLY WANT TO HURT ME', author: 'CULTURE CLUB', lang: 'EN'},
  {title: 'KARMA CHAMELEON', author: 'CULTURE CLUB', lang: 'EN'},
  {title: '(I JUST) DIED IN YOUR ARMS', author: 'CUTTING CREW', lang: 'EN'},
  {title: 'GIRLS JUST WANT TO HAVE FUN', author: 'CYNDI LAUPER', lang: 'EN'},
  {title: 'TIME AFTER TIME', author: 'CYNDI LAUPER', lang: 'EN'},
  {title: 'GET LUCKY', author: 'DAFT PUNK', lang: 'EN'},
  {title: 'LET\'S DANCE', author: 'DAVID BOWIE', lang: 'EN'},
  {title: 'LIFE ON MARS?', author: 'DAVID BOWIE', lang: 'EN'},
  {title: 'SPACE ODDITY', author: 'DAVID BOWIE', lang: 'EN'},
  {title: 'BREAKFAST AT TIFFANY\'S', author: 'DEEP BLUE SOMETHING', lang: 'EN'},
  {title: 'CHILD IN TIME', author: 'DEEP PURPLE', lang: 'EN'},
  {title: 'SMOKE ON THE WATER', author: 'DEEP PURPLE', lang: 'EN'},
  {title: 'ENJOY THE SILENCE', author: 'DEPECHE MODE', lang: 'EN'},
  {title: 'PERSONAL JESUS', author: 'DEPECHE MODE', lang: 'EN'},
  {title: 'VOYAGE, VOYAGE', author: 'DESIRELESS', lang: 'FR'},
  {title: 'COME ON EILEEN', author: 'DEXYS MIDNIGHT RUNNERS', lang: 'EN'},
  {title: 'MISIRLOU (IN PULP FICTION)', author: 'DICK DALE', lang: '-'},
  {title: 'BROTHERS IN ARMS', author: 'DIRE STRAITS', lang: 'EN'},
  {title: 'SULTANS OF SWING', author: 'DIRE STRAITS', lang: 'EN'},
  {title: 'JOLENE', author: 'DOLLY PARTON', lang: 'EN'},
  {title: 'AMERICAN PIE', author: 'DON MCLEAN', lang: 'EN'},
  {title: 'ROSE TATTO', author: 'DROPKICK MURPHYS', lang: 'EN'},
  {title: 'BARBRA STREISAND', author: 'DUCK SAUCE', lang: 'EN'},
  {title: 'SON OF A PREACHER MAN', author: 'DUSTY SPRINGFIELD', lang: 'EN'},
  {title: 'HOTEL CALIFORNIA', author: 'EAGLES', lang: 'EN'},
  {title: 'I SEE FIRE', author: 'ED SHEERAN', lang: 'EN'},
  {title: 'SHAPE OF YOU', author: 'ED SHEERAN', lang: 'EN'},
  {title: 'THINKING OUT LOUD', author: 'ED SHEERAN', lang: 'EN'},
  {title: 'EVENING OVER ROOFTOPS', author: 'EDGAR BROUGHTON BAND', lang: 'EN'},
  {title: 'NON, JE NE REGRETTE RIEN', author: 'EDITH PIAF', lang: 'FR'},
  {title: 'IN THE HALL OF THE MOUNTAIN KING', author: 'EDVARD GRIEG', lang: '-'},
  {title: 'HOME', author: 'EDWARD SHARPE & THE MAGNETIC ZEROS', lang: 'EN'},
  {title: 'I\'M BLUE', author: 'EIFFEL 65', lang: 'EN'},
  {title: 'MR. BLUE SKY', author: 'ELECTRIC LIGHT ORCHESTRA', lang: 'EN'},
  {title: 'CAN YOU FEEL THE LOVE TONIGHT', author: 'ELTON JOHN', lang: 'EN'},
  {title: 'I\'M STILL STANDING', author: 'ELTON JOHN', lang: 'EN'},
  {title: 'BLUE SUEDE SHOES', author: 'ELVIS PRESLEY', lang: 'EN'},
  {title: 'CAN\'T HELP FALLING IN LOVE', author: 'ELVIS PRESLEY', lang: 'EN'},
  {title: 'JAILHOUSE ROCK', author: 'ELVIS PRESLEY', lang: 'EN'},
  {title: 'LOSE YOURSELF', author: 'EMINEM', lang: 'EN'},
  {title: 'RAP GOD', author: 'EMINEM', lang: 'EN'},
  {title: 'WITHOUT ME', author: 'EMINEM', lang: 'EN'},
  {title: 'BAILANDO', author: 'ENRIQUE IGLESIAS', lang: 'ES'},
  {title: 'ORINOCO FLOW', author: 'ENYA', lang: 'EN'},
  {title: 'LAYLA', author: 'ERIC CLAPTON', lang: 'EN'},
  {title: 'TEARS IN HEAVEN', author: 'ERIC CLAPTON', lang: 'EN'},
  {title: 'SWEET DREAMS', author: 'EURITHMICS', lang: 'EN'},
  {title: 'THE FINAL COUNTDOWN', author: 'EUROPE', lang: 'EN'},
  {title: 'BRING ME TO LIFE', author: 'EVANESCENCE', lang: 'EN'},
  {title: 'DREAMS', author: 'FLEETWOOD MAC', lang: 'EN'},
  {title: 'LITTLE LIES', author: 'FLEETWOOD MAC', lang: 'EN'},
  {title: 'WHISTLE', author: 'FLO RIDA', lang: 'EN'},
  {title: 'NO LIGHT, NO LIGHT', author: 'FLORENCE + THE MACHINE', lang: 'EN'},
  {title: 'TOCA TOCA', author: 'FLY PROJECT', lang: 'EN'},
  {title: 'LEMON TREE', author: 'FOOL\'S GARDEN', lang: 'EN'},
  {title: 'PUMPED UP KICKS', author: 'FOSTER THE PEOPLE', lang: 'EN'},
  {title: 'OCCIDENTALI\'S KARMA', author: 'FRANCESCO GABBANI', lang: 'IT'},
  {title: 'SOMETHING STUPID', author: 'FRANK & NANCY SINATRA', lang: 'EN'},
  {title: 'FLY ME TO THE MOON', author: 'FRANK SINATRA', lang: 'EN'},
  {title: 'MY WAY', author: 'FRANK SINATRA', lang: 'EN'},
  {title: 'CAN\'T TAKE MY EYES OFF YOU', author: 'FRANKIE VALLI', lang: 'EN'},
  {title: 'FIRE', author: 'FRANZ FERDINAND', lang: 'EN'},
  {title: 'TAKE ME OUT', author: 'FRANZ FERDINAND', lang: 'EN'},
  {title: 'WALK AWAY', author: 'FRANZ FERDINAND', lang: 'EN'},
  {title: 'MAD WORLD', author: 'GARY JULES', lang: 'EN'},
  {title: 'SINGIN\' IN THE RAIN', author: 'GENE KELLY', lang: 'EN'},
  {title: 'MAMA', author: 'GENESIS', lang: 'EN'},
  {title: 'CARELESS WISPER (I\'M NEVER GONNA DANCE AGAIN)', author: 'GEORGE MICHAEL', lang: 'EN'},
  {title: 'BAKER STREET', author: 'GERRY RAFFERTY', lang: 'EN'},
  {title: 'THE RIDDLE', author: 'GIGI D\'AGOSTINO', lang: 'EN'},
  {title: 'I WILL SURVIVE', author: 'GLORIA GAYNOR', lang: 'EN'},
  {title: 'CRAZY', author: 'GNARLS BARKLEY', lang: 'EN'},
  {title: 'KALASHNIKOV', author: 'GORAN BREGOVIC', lang: 'EN'},
  {title: 'FEEL GOOD INC.', author: 'GORILLAZ', lang: 'EN'},
  {title: 'SOMEBODY THAT I USED TO KNOW', author: 'GOTYE', lang: 'EN'},
  {title: 'BOULEVARD OF BROKEN DREAMS', author: 'GREEN DAY', lang: 'EN'},
  {title: 'NOVEMBER RAIN', author: 'GUNS\'N\'ROSES', lang: 'EN'},
  {title: 'PARADISE CITY', author: 'GUNS\'N\'ROSES', lang: 'EN'},
  {title: 'SWEET CHILD OF MINE', author: 'GUNS\'N\'ROSES', lang: 'EN'},
  {title: 'WELCOME TO THE JUNGLE', author: 'GUNS\'N\'ROSES', lang: 'EN'},
  {title: 'WHAT IS LOVE? (BABY DON\'T HURT ME)', author: 'HADDAWAY', lang: 'EN'},
  {title: 'OVER THE RAINBOW', author: 'HAROLD ARLEN', lang: 'EN'},
  {title: 'TAKE ME TO CHURCH', author: 'HOZIER', lang: 'EN'},
  {title: 'LUST FOR LIFE', author: 'IGGY POP', lang: 'EN'},
  {title: 'THE PASSENGER', author: 'IGGY POP', lang: 'EN'},
  {title: 'BELIEVER', author: 'IMAGINE DRAGONS', lang: 'EN'},
  {title: 'RADIOACTIVE', author: 'IMAGINE DRAGONS', lang: 'EN'},
  {title: 'LET IT GO (FROM FROZEN)', author: 'INDINA MENZEL', lang: 'EN'},
  {title: 'JOHNNY I HARDLY KNEW YOU', author: 'IRISH ROVERS', lang: 'EN'},
  {title: 'IN-A-GADDA-DA-VIDA', author: 'IRON BUTTERFLY', lang: 'EN'},
  {title: 'FEAR OF THE DARK', author: 'IRON MAIDEN', lang: 'EN'},
  {title: 'YOU\'RE BEAUTIFUL', author: 'JAMES BLUNT', lang: 'EN'},
  {title: 'I FEEL GOOD', author: 'JAMES BROWN', lang: 'EN'},
  {title: 'THIS IS A MEN\'S WORLD', author: 'JAMES BROWN', lang: 'EN'},
  {title: 'TOCCATA AND FUGUE IN D MINOR', author: 'JAN S. BACH', lang: '-'},
  {title: '(TAKE ANOTHER) PIECE OF MY HEART', author: 'JANIS JOPLIN', lang: 'EN'},
  {title: 'I\'M YOURS', author: 'JASON MARZ', lang: 'EN'},
  {title: 'SOMEBODY TO LOVE', author: 'JEFFERSON\'S AIRPLANE', lang: 'EN'},
  {title: 'WHITE RABBIT', author: 'JEFFERSON\'S AIRPLANE', lang: 'EN'},
  {title: 'LET\'S GET LOUD', author: 'JENNIFER LOPEZ', lang: 'EN'},
  {title: 'ARE YOU GONNA BE MY GIRL', author: 'JET', lang: 'EN'},
  {title: 'ALL ALONG THE WATCHTOWER', author: 'JIMI HENDRIX', lang: 'EN'},
  {title: 'HEY JOE', author: 'JIMI HENDRIX', lang: 'EN'},
  {title: 'I LOVE ROCK \'N\' ROLL', author: 'JOAN JETT & THE BLACKHEARTS', lang: 'EN'},
  {title: 'WITH A LITTLE HELP FROM MY FRIENDS', author: 'JOE COCKER', lang: 'EN'},
  {title: 'LES CHAMPS ELYSEES', author: 'JOE DASSIN', lang: 'FR'},
  {title: 'COUNTRY ROADS', author: 'JOHN DENVER', lang: 'EN'},
  {title: 'IMAGINE', author: 'JOHN LENNON', lang: 'EN'},
  {title: 'SUMMER NIGHTS (FROM GREASE)', author: 'JOHN TRAVOLTA & OLIVIA NEWTON-JOHN', lang: 'EN'},
  {title: 'YOU\'RE THE ONE THAT I WANT (FROM GREASE)', author: 'JOHN TRAVOLTA & OLIVIA NEWTON-JOHN', lang: 'EN'},
  {title: 'I WALK THE LINE', author: 'JOHNNY CASH', lang: 'EN'},
  {title: 'DON\'T STOP BELIEVIN\'', author: 'JOURNEY', lang: 'EN'},
  {title: 'LA CAMISA NEGRA', author: 'JUANES', lang: 'ES'},
  {title: 'COLORS OF THE WIND (POCAHONTAS)', author: 'JUDY KUHN', lang: 'EN'},
  {title: 'RUBY', author: 'KAISER CHIEFS', lang: 'EN'},
  {title: 'DUST IN THE WIND', author: 'KANSAS', lang: 'EN'},
  {title: 'NINE MILLION BICYCLES', author: 'KATIE MELUA', lang: 'EN'},
  {title: 'HOT N COLD', author: 'KATY PERRY', lang: 'EN'},
  {title: 'I KISSED A GIRL', author: 'KATY PERRY', lang: 'EN'},
  {title: 'ROAR', author: 'KATY PERRY', lang: 'EN'},
  {title: 'NIGHTCALL (FROM DRIVE)', author: 'KAVINSKY', lang: 'EN'},
  {title: 'STRONGER', author: 'KELLY CLARKSON', lang: 'EN'},
  {title: 'TIK TOK', author: 'KESHA', lang: 'EN'},
  {title: 'EPITAPH', author: 'KING CRIMSON', lang: 'EN'},
  {title: 'THE COURT OF THE CRIMSON KING', author: 'KING CRIMSON', lang: 'EN'},
  {title: 'SEX ON FIRE', author: 'KINGS OF LEON', lang: 'EN'},
  {title: 'COME WITH ME NOW', author: 'KONGOS', lang: 'EN'},
  {title: 'LADY MARMALADE (VOULEZ-VOUS COUCHER AVEC MOI)', author: 'LABELLE', lang: 'EN'},
  {title: 'ALEJANDRO', author: 'LADY GAGA', lang: 'EN'},
  {title: 'BAD ROMANCE', author: 'LADY GAGA', lang: 'EN'},
  {title: 'POKER FACE', author: 'LADY GAGA', lang: 'EN'},
  {title: '\'T SMIDJE', author: 'LAÏS', lang: '-'},
  {title: 'YOUNG AND BEAUTIFUL', author: 'LANA DEL REY', lang: 'EN'},
  {title: 'ASEREJÉ', author: 'LAS KETCHUP', lang: 'ES'},
  {title: 'IMMIGRANT SONG', author: 'LED ZEPPELIN', lang: 'EN'},
  {title: 'STAIRWAY TO HEAVEN', author: 'LED ZEPPELIN', lang: 'EN'},
  {title: 'WHOLE LOTTA LOVE', author: 'LED ZEPPELIN', lang: 'EN'},
  {title: 'FLY AWAY', author: 'LENNY KRAVITZ', lang: 'EN'},
  {title: 'HALLELUJAH', author: 'LEONARD COHEN', lang: 'EN'},
  {title: 'NUMB', author: 'LINKIN PARK', lang: 'EN'},
  {title: 'SAY YOU, SAY ME', author: 'LIONEL RICHIE', lang: 'EN'},
  {title: 'NARCOTIC', author: 'LIQUIDO', lang: 'EN'},
  {title: 'PARTY ROCK ANTHEM', author: 'LMFAO', lang: 'EN'},
  {title: 'MACARENA', author: 'LOS DEL RIO', lang: 'ES'},
  {title: 'WHAT A WONDERFUL WORLD', author: 'LOUIS ARMSTRONG', lang: 'EN'},
  {title: 'DANZA KUDURO', author: 'LUCENZO & DON OMAR', lang: 'ES'},
  {title: 'FÜR ELISE', author: 'LUDWIG VAN BEETHOVEN', lang: '-'},
  {title: 'DESPACITO', author: 'LUIS FONSI', lang: 'ES'},
  {title: 'SWEET HOME ALABAMA', author: 'LYNYRD SKYNYRD', lang: 'EN'},
  {title: 'CAN\'T HOLD US', author: 'MACKLEMORE', lang: 'EN'},
  {title: 'THRIFT SHOP', author: 'MACKLEMORE', lang: 'EN'},
  {title: 'OUR HOUSE', author: 'MADNESS', lang: 'EN'},
  {title: 'LIKE A VIRGIN', author: 'MADONNA', lang: 'EN'},
  {title: 'MATERIAL GIRL', author: 'MADONNA', lang: 'EN'},
  {title: 'LEAN ON', author: 'MAJOR LAZER', lang: 'EN'},
  {title: 'MOVES LIKE JAGGER', author: 'MAROON 5', lang: 'EN'},
  {title: 'SUGAR', author: 'MAROON 5', lang: 'EN'},
  {title: 'THIS LOVE', author: 'MAROON 5', lang: 'EN'},
  {title: 'NOTHING ELSE MATTERS', author: 'METALLICA', lang: 'EN'},
  {title: 'KIDS', author: 'MGMT', lang: 'EN'},
  {title: 'BEAT IT', author: 'MICHAEL JACKSON', lang: 'EN'},
  {title: 'BILLIE JEAN', author: 'MICHAEL JACKSON', lang: 'EN'},
  {title: 'SMOOTH CRILIMAL', author: 'MICHAEL JACKSON', lang: 'EN'},
  {title: 'THRILLER', author: 'MICHAEL JACKSON', lang: 'EN'},
  {title: 'AI SE EU TE PEGO', author: 'MICHEL TELÓ', lang: 'ES'},
  {title: 'RELAX, TAKE IT EASY', author: 'MIKA', lang: 'EN'},
  {title: 'ALWAYS LOOK ON THE BRIGHT SIDE OF LIFE', author: 'MONTY PYTHON', lang: 'EN'},
  {title: 'THE CAVE', author: 'MUMFORD & SONS', lang: 'EN'},
  {title: 'SUPERMASSIVE BLACK HOLE', author: 'MUSE', lang: 'EN'},
  {title: 'BANG BANG (MY BABY SHOT ME DOWN)', author: 'NANCY SINATRA', lang: 'EN'},
  {title: 'THESE BOOTS ARE MADE FOR WALKIN\'', author: 'NANCY SINATRA', lang: 'EN'},
  {title: 'SUMMER WINE', author: 'NANCY SINATRA & LEE HAZLEWOOD', lang: 'EN'},
  {title: 'HOW YOU REMIND ME', author: 'NICKELBACK', lang: 'EN'},
  {title: 'FEELING GOOD', author: 'NINA SIMONE / MICHAEL BUBLÉ', lang: 'EN'},
  {title: 'COME AS YOU ARE', author: 'NIRVANA', lang: 'EN'},
  {title: 'SMELLS LIKE TEEN SPRIT', author: 'NIRVANA', lang: 'EN'},
  {title: 'DON\'T SPEAK', author: 'NO DOUBT', lang: 'EN'},
  {title: 'JUST A GIRL', author: 'NO DOUBT', lang: 'EN'},
  {title: 'DRAGOSTEA DIN TEI (NUMA NUMA JEJ)', author: 'O-ZONE', lang: 'RO'},
  {title: 'WONDERWALL', author: 'OASIS', lang: 'EN'},
  {title: 'DIRTY PAWS', author: 'OF MONSTERS AND MEN', lang: 'EN'},
  {title: 'GYONGYHAJU LANY (THE GIRL WITH PEARLY HAIR)', author: 'OMEGA', lang: 'HU'},
  {title: 'COUNTING STARS', author: 'ONEREPUBLIC', lang: 'EN'},
  {title: 'BOOTY SWING', author: 'PAROV STELAR', lang: 'EN'},
  {title: 'LET HER GO', author: 'PASSENGER', lang: 'EN'},
  {title: 'BECAUSE THE NIGHT', author: 'PATTI SMITH', lang: 'EN'},
  {title: 'ALIVE', author: 'PEARL JAM', lang: 'EN'},
  {title: 'ALWAYS ON MY MIND', author: 'PET SHOP BOYS', lang: 'EN'},
  {title: 'DOWNTOWN', author: 'PETULA CLARCK', lang: 'EN'},
  {title: 'HAPPY', author: 'PHARRELL WILLIAMS', lang: 'EN'},
  {title: 'ANOTHER DAY IN PARADISE', author: 'PHIL COLLINS', lang: 'EN'},
  {title: 'ANOTHER BRICK IN THE WALL', author: 'PINK FLOYD', lang: 'EN'},
  {title: 'HEY YOU', author: 'PINK FLOYD', lang: 'EN'},
  {title: 'HIGH HOPES', author: 'PINK FLOYD', lang: 'EN'},
  {title: 'MONEY', author: 'PINK FLOYD', lang: 'EN'},
  {title: 'SHINE ON YOU CRAZY DIAMOND', author: 'PINK FLOYD', lang: 'EN'},
  {title: 'WISH YOU WERE HERE', author: 'PINK FLOYD', lang: 'EN'},
  {title: 'TIMBER', author: 'PITBULL', lang: 'EN'},
  {title: 'WHERE IS MY MIND?', author: 'PIXIES', lang: 'EN'},
  {title: 'PURPLE RAIN', author: 'PRINCE', lang: 'EN'},
  {title: 'GANGAM STYLE', author: 'PSY', lang: 'KO'},
  {title: 'BOHEMIAN RHAPSODY', author: 'QUEEN', lang: 'EN'},
  {title: 'RADIO GAGA', author: 'QUEEN', lang: 'EN'},
  {title: 'THE SHOW MUST GO ON', author: 'QUEEN', lang: 'EN'},
  {title: 'WE ARE THE CHAMPIONS', author: 'QUEEN', lang: 'EN'},
  {title: 'WE WILL ROCK YOU', author: 'QUEEN', lang: 'EN'},
  {title: 'I BELIEVE I CAN FLY', author: 'R. KELLY', lang: 'EN'},
  {title: 'EVERYBODY HURTS', author: 'R.E.M.', lang: 'EN'},
  {title: 'IT\'S THE END OF THE WORLD THAT WE KNOW IT', author: 'R.E.M.', lang: 'EN'},
  {title: 'LOSING MY RELIGION', author: 'R.E.M.', lang: 'EN'},
  {title: 'CREEP', author: 'RADIOHEAD', lang: 'EN'},
  {title: 'KARMA POLICE', author: 'RADIOHEAD', lang: 'EN'},
  {title: 'HIT THE ROAD JACK', author: 'RAY CHARLES', lang: 'EN'},
  {title: 'FOR AMERICA', author: 'RED BOX', lang: 'EN'},
  {title: 'CALIFORNICATION', author: 'RED HOT CHILI PEPPERS', lang: 'EN'},
  {title: 'SNOW (HEY OH)', author: 'RED HOT CHILI PEPPERS', lang: 'EN'},
  {title: 'UNDER THE BRIDGE', author: 'RED HOT CHILI PEPPERS', lang: 'EN'},
  {title: 'NEVER GONNA GIVE YOU UP', author: 'RICK ASTLEY', lang: 'EN'},
  {title: 'UMBRELLA', author: 'RIHANNA', lang: 'EN'},
  {title: 'LA BAMBA', author: 'RITCHIE VALENS', lang: 'ES'},
  {title: 'BLURRED LINES', author: 'ROBIN THICKE, PHARRELL WILLIAMS & T.I.', lang: 'EN'},
  {title: 'LISTEN TO YOUR HEART', author: 'ROXETTE', lang: 'EN'},
  {title: 'OH, PRETTY WOMAN', author: 'ROY ORBISON', lang: 'EN'},
  {title: 'DA COCONUT NUT (COCONUT SONG)', author: 'RYAN CAYABYAB', lang: 'EN'},
  {title: 'SMOOTH', author: 'SANTANA & ROB THOMAS', lang: 'EN'},
  {title: 'WIND OF CHANGE', author: 'SCORPIONS', lang: 'EN'},
  {title: 'SAN FRANSISCO', author: 'SCOTT MCKENZIE', lang: 'EN'},
  {title: 'HIPS DON\'T LIE', author: 'SHAKIRA', lang: 'EN'},
  {title: 'WAKA WAKA', author: 'SHAKIRA', lang: 'EN'},
  {title: 'SEÑORITA', author: 'SHAWN MENDES, CAMILA CABELLO', lang: 'EN'},
  {title: 'MRS ROBINSON', author: 'SIMON & GARFUNKEL', lang: 'EN'},
  {title: 'THE SOUND OF SILENCE', author: 'SIMON & GARFUNKEL', lang: 'EN'},
  {title: 'ALL STAR', author: 'SMASH MOUTH', lang: 'EN'},
  {title: 'BLACK HOLE SUN', author: 'SOUNDGARDEN', lang: 'EN'},
  {title: 'WANNABE', author: 'SPICE GIRLS', lang: 'EN'},
  {title: 'BORN TO BE WILD', author: 'STEPPENWOLF', lang: 'EN'},
  {title: 'ENGLISHMAN IN NEW YORK', author: 'STING', lang: 'EN'},
  {title: 'FIELDS OF GOLD', author: 'STING', lang: 'EN'},
  {title: 'SHAPE OF MY HEART', author: 'STING', lang: 'EN'},
  {title: 'LONELY DAY', author: 'SYSTEM OF A DOWN', lang: 'EN'},
  {title: 'IT FEELS LIKE I\'M ONLY GOING BACKWARDS', author: 'TAME IMPALA', lang: 'EN'},
  {title: 'NAS NE DOGONYAT', author: 'TATU', lang: 'RU'},
  {title: 'SHAKE IT OFF', author: 'TAYLOR SWIFT', lang: 'EN'},
  {title: 'SHOUT', author: 'TEARS FOR FEARS', lang: 'EN'},
  {title: 'BEELZEBOSS', author: 'TENACIOUS D', lang: 'EN'},
  {title: 'KICKAPOO', author: 'TENACIOUS D', lang: 'EN'},
  {title: 'THE HOUSE OF THE RISING SUN', author: 'THE ANIMALS', lang: 'EN'},
  {title: 'COME TOGETHER', author: 'THE BEATLES', lang: 'EN'},
  {title: 'HEY JUDE', author: 'THE BEATLES', lang: 'EN'},
  {title: 'LET IT BE', author: 'THE BEATLES', lang: 'EN'},
  {title: 'YELLOW SUBMARINE', author: 'THE BEATLES', lang: 'EN'},
  {title: 'YESTERDAY', author: 'THE BEATLES', lang: 'EN'},
  {title: 'LONELY BOY', author: 'THE BLACK KEYS', lang: 'EN'},
  {title: 'VIDEO KILLED THE RADIO STA', author: 'THE BUGGLES ', lang: 'EN'},
  {title: 'TEQUILA', author: 'THE CHAMPS', lang: 'EN'},
  {title: 'MR. SANDMAN', author: 'THE CHORDETTES', lang: 'EN'},
  {title: 'ZOMBIE', author: 'THE CRANBERRIES', lang: 'EN'},
  {title: 'FRIDAY I\'M IN LOVE', author: 'THE CURE', lang: 'EN'},
  {title: 'LIGHT MY FIRE', author: 'THE DOORS', lang: 'EN'},
  {title: 'PEOPLE ARE STRANGE', author: 'THE DOORS', lang: 'EN'},
  {title: 'RIDERS ON THE STORM', author: 'THE DOORS', lang: 'EN'},
  {title: 'IRIS', author: 'THE GOO GOO DALLS', lang: 'EN'},
  {title: 'I WANT YOU BACK', author: 'THE JACKSON 5', lang: 'EN'},
  {title: 'YOU REALLY GOT ME', author: 'THE KINKS', lang: 'EN'},
  {title: 'MY SHARONA', author: 'THE KNACK', lang: 'EN'},
  {title: 'BAD HABIT', author: 'THE KOOKS', lang: 'EN'},
  {title: 'CALIFORNIA DREAMIN\'', author: 'THE MAMAS AND THE PAPAS', lang: 'EN'},
  {title: 'I\'M A BELIEVER', author: 'THE MONKEES', lang: 'EN'},
  {title: 'NIGHTS IN WHITE SATIN', author: 'THE MOODY BLUES', lang: 'EN'},
  {title: 'PRETTY FLY (FOR A WHITE GUY)', author: 'THE OFFSPRING', lang: 'EN'},
  {title: 'YOU\'RE GONNA GO FAR, KID', author: 'THE OFFSPRING', lang: 'EN'},
  {title: 'EVERY BREATH YOU TAKE', author: 'THE POLICE', lang: 'EN'},
  {title: 'ROXANNE', author: 'THE POLICE', lang: 'EN'},
  {title: 'I\'M GONNA BE (500 MILES)', author: 'THE PROCLAIMERS', lang: 'EN'},
  {title: 'FIRESTARTER', author: 'THE PRODIGY', lang: 'EN'},
  {title: 'I\'LL BE THERE FOR YOU', author: 'THE REMBRANDTS', lang: 'EN'},
  {title: '(I CAN\'T GET NO) SATISFACTION', author: 'THE ROLLING STONES', lang: 'EN'},
  {title: 'GIMME SHELTER', author: 'THE ROLLING STONES', lang: 'EN'},
  {title: 'PAINT IT BLACK', author: 'THE ROLLING STONES', lang: 'EN'},
  {title: 'SUGAR BABY LOVE', author: 'THE RUBETTES', lang: 'EN'},
  {title: 'GOLDEN BROWN', author: 'THE STRANGLERS', lang: 'EN'},
  {title: 'WILD THING', author: 'THE TROGGS', lang: 'EN'},
  {title: 'HAPPY TOGETHER', author: 'THE TURTLES', lang: 'EN'},
  {title: 'BITTER-SWEET SYMPHONY', author: 'THE VERVE', lang: 'EN'},
  {title: 'SEVEN NATION ARMY', author: 'THE WHITE STRIPES', lang: 'EN'},
  {title: 'BABA O\'RILEY', author: 'THE WHO', lang: 'EN'},
  {title: 'MY GENERATION', author: 'THE WHO', lang: 'EN'},
  {title: 'HAKUNA MATATA', author: 'TIM RICE & ELTON JOHN', lang: 'EN'},
  {title: '(SIMPLY) THE BEST', author: 'TINA TURNER', lang: 'EN'},
  {title: 'GOLDENEYE', author: 'TINA TURNER', lang: 'EN'},
  {title: 'WHAT\'S LOVE GOT TO DO WITH IT', author: 'TINA TURNER', lang: 'EN'},
  {title: 'IT\'S NOT UNUSUAL', author: 'TOM JONES', lang: 'EN'},
  {title: 'SEXBOMB', author: 'TOM JONES', lang: 'EN'},
  {title: 'DANCING IN THE MOONLIGHT', author: 'TOPLOADER', lang: 'EN'},
  {title: 'AFRICA', author: 'TOTO', lang: 'EN'},
  {title: 'STRESSED OUT', author: 'TWENTY ONE PILOTS', lang: 'EN'},
  {title: 'I STILL HAVEN\'T FOUND WHAT I\'M LOOKING FOR', author: 'U2', lang: 'EN'},
  {title: 'PRIDE (IN THE NAME OF LOVE)', author: 'U2', lang: 'EN'},
  {title: 'WITH OR WITHOUT YOU', author: 'U2', lang: 'EN'},
  {title: 'WE ARE THE WORLD', author: 'USA FOR AFRICA', lang: 'EN'},
  {title: 'BROWN EYED GIRL', author: 'VAN MORRISON', lang: 'EN'},
  {title: 'CHARIOTS OF FIRE', author: 'VANGELIS', lang: 'EN'},
  {title: 'CONQUEST OF PARADISE (1492)', author: 'VANGELIS', lang: 'EN'},
  {title: 'ICE ICE BABY', author: 'VANILLA ICE', lang: 'EN'},
  {title: 'LOVE IS ALL AROUND', author: 'WET WET WET', lang: 'EN'},
  {title: 'LAST CHRISTMAS', author: 'WHAM!', lang: 'EN'},
  {title: 'WAKE ME UP BEFORE YOU GO', author: 'WHAM!', lang: 'EN'},
  {title: 'I WILL ALWAYS LOVE YOU', author: 'WHITNEY HOUSTON', lang: 'EN'},
  {title: 'SEE YOU AGAIN', author: 'WIZ KHALIFA', lang: 'EN'},
  {title: 'EINE KLEINE NACHTMUSIK', author: 'WOLFGANG A. MOZART', lang: '-'},
  {title: 'OWNER OF THE LONELY HEART', author: 'YES', lang: 'EN'},
  {title: 'WHAT DOES THE FOX SAY?', author: 'YLVIS', lang: 'EN'},
  {title: 'LA GRANGE', author: 'ZZ TOP', lang: 'EN'},
  {title: 'BELLA CIAO', author: '', lang: 'IT'},
  {title: 'BENNY HILL THEME', author: '', lang: 'EN'},
  {title: 'GODFATHER THEME', author: '', lang: '-'},
  {title: 'HARRY POTTER THEME', author: '', lang: '-'},
  {title: 'IMPERIAL MARCH (STAR WARS)', author: '', lang: '-'},
  {title: 'JAMES BOND THEME', author: '', lang: '-'},
  {title: 'MCDONALDS JINGLE', author: '', lang: 'EN'},
  {title: 'CHODŹ, POMALUJ MÓJ ŚWIAT', author: '2 PLUS 1', lang: 'PL'},
  {title: 'PRZEZ TWE OCZY ZIELONE', author: 'AKCENT', lang: 'PL'},
  {title: 'LUBIĘ MÓWIĆ Z TOBĄ', author: 'AKURAT', lang: 'PL'},
  {title: 'CZTERDZIESTOLATEK', author: 'ANDRZEJ ROSIEWICZ', lang: 'PL'},
  {title: 'BYŁAŚ SERCA BICIEM', author: 'ANDRZEJ ZAUCHA', lang: 'PL'},
  {title: 'GUMISIE', author: 'ANDRZEJ ZAUCHA', lang: 'PL'},
  {title: 'I WSZYSTKO SIĘ MOŻE ZDARZYĆ', author: 'ANITA LIPNICKA', lang: 'PL'},
  {title: 'MOJE JEDYNE MARZENIE (PRZETAŃCZYĆ Z TOBĄ CHCĘ)', author: 'ANNA JANTAR', lang: 'PL'},
  {title: 'TYLE SŁOŃCA W CAŁYM MIEŚCIE', author: 'ANNA JANTAR', lang: 'PL'},
  {title: 'ŚWIĘTY, ŚWIĘTY UŚMIECHNIĘTY', author: 'ARKA NOEGO', lang: 'PL'},
  {title: 'SKÓRA', author: 'AYA RL', lang: 'PL'},
  {title: 'BIAŁY MIŚ', author: 'BADYLE', lang: 'PL'},
  {title: 'BIAŁA ARMIA', author: 'BAJM', lang: 'PL'},
  {title: 'MYŚLI I SŁOWA', author: 'BAJM', lang: 'PL'},
  {title: 'DRES', author: 'BIG CYC', lang: 'PL'},
  {title: 'FACET TO ŚWINIA', author: 'BIG CYC', lang: 'PL'},
  {title: 'MAKUMBA', author: 'BIG CYC', lang: 'PL'},
  {title: 'RUDY SIĘ ŻENI', author: 'BIG CYC', lang: 'PL'},
  {title: 'W DZIEŃ GORĄCEGO LATA', author: 'BIG DAY', lang: 'PL'},
  {title: 'DO NIEBA, DO PIEKŁA', author: 'BLUE CAFE', lang: 'PL'},
  {title: 'DAJ Z SIEBIE WSZYSTKO', author: 'BOB ONE FT. BAS TAJPAN', lang: 'PL'},
  {title: 'JESTEŚ SZALONA', author: 'BOYS', lang: 'PL'},
  {title: 'JANKO, JANECZKO', author: 'BRACIA FIGO FAGOT', lang: 'PL'},
  {title: 'WÓDA ZRYJE BANIĘ', author: 'BRACIA FIGO FAGOT', lang: 'PL'},
  {title: 'CZERWONE KORALE', author: 'BRATHANKI', lang: 'PL'},
  {title: 'W KINIE W LUBLINIE', author: 'BRATHANKI', lang: 'PL'},
  {title: 'KIEDY BYŁEM MAŁYM CHŁOPCEM', author: 'BREAKOUT', lang: 'PL'},
  {title: 'GRANDA', author: 'BRODKA', lang: 'PL'},
  {title: 'MIAŁ BYĆ ŚLUB', author: 'BRODKA', lang: 'PL'},
  {title: 'BAL WSZYSTKICH ŚWIĘTYCH', author: 'BUDKA SUFLERA', lang: 'PL'},
  {title: 'JOLKA, JOLKA PAMIĘTASZ', author: 'BUDKA SUFLERA', lang: 'PL'},
  {title: 'TAKIE TANGO', author: 'BUDKA SUFLERA', lang: 'PL'},
  {title: 'ZA OSTATNI GROSZ', author: 'BUDKA SUFLERA', lang: 'PL'},
  {title: 'KOCHAM WOLNOŚĆ', author: 'CHŁOPCY Z PLACU BRONI', lang: 'PL'},
  {title: 'LESZEK ŻUKOWSKI (NICZEGO NIE BĘDZIE ŻAL)', author: 'COMA', lang: 'PL'},
  {title: 'NOGI', author: 'CZARNO CZARNI', lang: 'PL'},
  {title: 'ANNA MARIA', author: 'CZERWONE GITARY', lang: 'PL'},
  {title: 'DOZWOLONE OD LAT OSIEMNASTU', author: 'CZERWONE GITARY', lang: 'PL'},
  {title: 'KWIATY WE WŁOSACH', author: 'CZERWONE GITARY', lang: 'PL'},
  {title: 'NIE ZADZIERAJ NOSA', author: 'CZERWONE GITARY', lang: 'PL'},
  {title: 'DZIWNY JEST TEN ŚWIAT', author: 'CZESŁAW NIEMEN', lang: 'PL'},
  {title: 'SEN O WARSZAWIE', author: 'CZESŁAW NIEMEN', lang: 'PL'},
  {title: 'MASZYNKA DO ŚWIERKANIA', author: 'CZESŁAW ŚPIEWA', lang: 'PL'},
  {title: 'MAŁOMIASTECZKOWY', author: 'DAWID PODSIADŁO', lang: 'PL'},
  {title: 'NIE MA FAL', author: 'DAWID PODSIADŁO', lang: 'PL'},
  {title: 'NIEZNAJOMY', author: 'DAWID PODSIADŁO', lang: 'PL'},
  {title: 'KOCHAĆ INACZEJ', author: 'DE MONO', lang: 'PL'},
  {title: 'STATKI NA NIEBIE', author: 'DE MONO', lang: 'PL'},
  {title: 'NIE DAJ SIĘ', author: 'DODA', lang: 'PL'},
  {title: 'MY SŁOWIANIE', author: 'DONATAN CLEO', lang: 'PL'},
  {title: 'CZERWONY JAK CEGŁA', author: 'DŻEM', lang: 'PL'},
  {title: 'WEHIKUŁ CZASU', author: 'DŻEM', lang: 'PL'},
  {title: 'WHISKY', author: 'DŻEM', lang: 'PL'},
  {title: 'CZTEREJ PANCERNI I PIES (DESZCZE NIESPOKOJNE)', author: 'EDMUND FETTING', lang: 'PL'},
  {title: 'TO NIE JA', author: 'EDYTA GÓRNIAK', lang: 'PL'},
  {title: 'DUMKA NA DWA SERCA', author: 'EDYTA GORNIAK I MIETEK SZCZESNIAK', lang: 'PL'},
  {title: 'DZIECI', author: 'ELEKTRYCZNE GITARY', lang: 'PL'},
  {title: 'KAMIEŃ Z NAPISEM LOVE', author: 'ENEJ', lang: 'PL'},
  {title: 'JUŻ TAKI JESTEM ZIMNY DRAŃ', author: 'EUGENIUSZ BODO', lang: 'PL'},
  {title: 'UMÓWIŁEM SIĘ Z NIĄ NA DZIEWIĄTĄ', author: 'EUGENIUSZ BODO', lang: 'PL'},
  {title: 'ŻAŁUJĘ', author: 'EWELINA FLINTA', lang: 'PL'},
  {title: 'W STRONĘ SŁOŃCA', author: 'EWELINA LISOWSKA', lang: 'PL'},
  {title: 'CHCĘ TU ZOSTAĆ', author: 'FARBA', lang: 'PL'},
  {title: 'MYDŁO LUBI ZABAWĘ', author: 'FASOLKI', lang: 'PL'},
  {title: 'A GDY JEST JUŻ CIEMNO', author: 'FEEL', lang: 'PL'},
  {title: 'JAK ANIOŁA GŁOS', author: 'FEEL', lang: 'PL'},
  {title: 'LATO', author: 'FORMACJA NIEŻYWYCH SCHABUFF', lang: 'PL'},
  {title: 'KING BRUCE LEE KARATE MISTRZ', author: 'FRANEK KIMONO', lang: 'PL'},
  {title: 'ŚCIERNISCO', author: 'GOLEC UORKIESTRA', lang: 'PL'},
  {title: 'SŁODYCZE', author: 'GOLEC UORKIESTRA', lang: 'PL'},
  {title: 'NA SZCZYCIE', author: 'GRUBSON', lang: 'PL'},
  {title: 'CICHOSZA', author: 'GRZEGORZ TURNAU', lang: 'PL'},
  {title: 'NAPRAWDĘ NIE DZIEJE SIĘ NIC', author: 'GRZEGORZ TURNAU', lang: 'PL'},
  {title: 'ZANIM PÓJDĘ', author: 'HAPPYSAD', lang: 'PL'},
  {title: 'RUDY RYDZ', author: 'HELENA MAJDANIEC', lang: 'PL'},
  {title: '[SIC!]', author: 'HEY', lang: 'PL'},
  {title: 'MOJA I TWOJA NADZIEJA', author: 'HEY', lang: 'PL'},
  {title: 'A WSZYSTKO TO...', author: 'ICH TROJE', lang: 'PL'},
  {title: 'KEINE GRENZEN (ŻADNYCH GRANIC)', author: 'ICH TROJE', lang: 'PL'},
  {title: 'ZAWSZE Z TOBĄ CHCIAŁBYM BYĆ', author: 'ICH TROJE', lang: 'PL'},
  {title: 'NADZIEJA', author: 'IRA', lang: 'PL'},
  {title: 'JEJ CZARNE OCZY', author: 'IVAN I DELFIN', lang: 'PL'},
  {title: 'MURY', author: 'JACEK KACZMARSKI', lang: 'PL'},
  {title: 'NASZA KLASA', author: 'JACEK KACZMARSKI', lang: 'PL'},
  {title: 'POLICEMAN', author: 'JAMAL', lang: 'PL'},
  {title: 'BRUNETKI, BLONDYNKI', author: 'JAN KIEPURA', lang: 'PL'},
  {title: 'KOKO KOKO EURO SPOKO', author: 'JARZĘBINA', lang: 'PL'},
  {title: 'JAK ZAPOMNIEĆ', author: 'JEDEN OSIEM L', lang: 'PL'},
  {title: 'BO Z DZIEWCZYNAMI', author: 'JERZY POŁOMSKI', lang: 'PL'},
  {title: 'PAMIĘTAJCIE O OGRODACH', author: 'JONASZ KOFTA', lang: 'PL'},
  {title: 'ZA KAŻDYM RAZEM', author: 'JULA', lang: 'PL'},
  {title: 'DZIEWCZYNA SZAMANA', author: 'JUSTYNA STECZKOWSKA', lang: 'PL'},
  {title: 'MACZO', author: 'K.A.S.A.', lang: 'PL'},
  {title: 'PLUS I MINUS', author: 'KALIBER 44', lang: 'PL'},
  {title: 'EXPLOSION', author: 'KALWI & REMI', lang: 'PL'},
  {title: 'ZABIORĘ CIĘ WŁAŚNIE TAM', author: 'KANCELARIA', lang: 'PL'},
  {title: 'LEPSZY MODEL', author: 'KASIA KLICH', lang: 'PL'},
  {title: 'NOBODY', author: 'KASIA KOWALSKA', lang: 'PL'},
  {title: 'PROWADŹ MNIE', author: 'KASIA KOWALSKA', lang: 'PL'},
  {title: 'NIE BĄDŹ TAKI SZYBKI BILL', author: 'KASIA SOBCZYK', lang: 'PL'},
  {title: 'O MNIE SIĘ NIE MARTW', author: 'KASIA SOBCZYK', lang: 'PL'},
  {title: 'TESTOSTERON', author: 'KAYAH', lang: 'PL'},
  {title: 'PRAWY DO LEWEGO', author: 'KAYAH, BREGOVIC', lang: 'PL'},
  {title: 'ŚPIJ, KOCHANIE ŚPIJ', author: 'KAYAH, BREGOVIC', lang: 'PL'},
  {title: '12 GROSZY', author: 'KAZIK', lang: 'PL'},
  {title: 'KOCHAM CIĘ JAK IRLANDIĘ', author: 'KOBRANOCKA', lang: 'PL'},
  {title: 'SŁODKIEGO MIŁEGO ŻYCIA', author: 'KOMBI', lang: 'PL'},
  {title: 'POKOLENIE', author: 'KOMBII', lang: 'PL'},
  {title: 'BO JESTEŚ TY', author: 'KRZYSZTOF KRAWCZYK', lang: 'PL'},
  {title: 'PAROSTATEK', author: 'KRZYSZTOF KRAWCZYK', lang: 'PL'},
  {title: 'MÓJ PRZYJACIELU', author: 'KRZYSZTOF KRAWCZYK & GORAN BREGOVIC', lang: 'PL'},
  {title: 'TRUDNO TAK', author: 'KRZYSZTOF KRAWCZYK, EDYTA BARTOSIEWICZ', lang: 'PL'},
  {title: 'KULFON CO Z CIEBIE WYROŚNIE?', author: 'KULFON I MONIKA', lang: 'PL'},
  {title: 'ARAHJA', author: 'KULT', lang: 'PL'},
  {title: 'BARANEK', author: 'KULT', lang: 'PL'},
  {title: 'BROOKLYŃSKA RADA ŻYDÓW', author: 'KULT', lang: 'PL'},
  {title: 'DO ANI', author: 'KULT', lang: 'PL'},
  {title: 'GDY NIE MA DZIECI', author: 'KULT', lang: 'PL'},
  {title: 'DZIŚ PÓŹNO PÓJDĘ SPAĆ', author: 'KWIAT JABŁONI', lang: 'PL'},
  {title: 'JAMMIN', author: 'LADY PANK', lang: 'PL'},
  {title: 'KRYZYSOWA NARZYCZONA', author: 'LADY PANK', lang: 'PL'},
  {title: 'MNIEJ NIŻ ZERO', author: 'LADY PANK', lang: 'PL'},
  {title: 'NA CO KOMU DZIŚ', author: 'LADY PANK', lang: 'PL'},
  {title: 'STACJA WARSZAWA', author: 'LADY PANK', lang: 'PL'},
  {title: 'TACY SAMI', author: 'LADY PANK', lang: 'PL'},
  {title: 'TAŃCZ GŁUPIA, TAŃCZ', author: 'LADY PANK', lang: 'PL'},
  {title: 'ZAWSZE TAM GDZIE TY', author: 'LADY PANK', lang: 'PL'},
  {title: 'HYDROPIEKŁOWSTĄPIENIE', author: 'LAO CHE', lang: 'PL'},
  {title: 'WOJENKA', author: 'LAO CHE', lang: 'PL'},
  {title: 'ŻYCIE JEST JAK TRAMWAJ', author: 'LAO CHE', lang: 'PL'},
  {title: 'ONA CZUJE WE MNIE PINIĄDZ', author: 'ŁOBUZY', lang: 'PL'},
  {title: 'PRZEŻYJ TO SAM', author: 'LOMBARD', lang: 'PL'},
  {title: 'SZKLANA POGODA', author: 'LOMBARD', lang: 'PL'},
  {title: 'AGNIESZKA', author: 'ŁZY', lang: 'PL'},
  {title: 'NARCYZ', author: 'ŁZY', lang: 'PL'},
  {title: 'OCZY SZEROKO ZAMKNIĘTE', author: 'ŁZY', lang: 'PL'},
  {title: 'CYKADY NA CYKLADACH', author: 'MAANAM', lang: 'PL'},
  {title: 'KOCHAM CIĘ KOCHANIE MOJE', author: 'MAANAM', lang: 'PL'},
  {title: 'KRAKOWSKI SPLEEN', author: 'MAANAM', lang: 'PL'},
  {title: 'SZARE MIRAŻE', author: 'MAANAM', lang: 'PL'},
  {title: 'AICHA', author: 'MAGMA', lang: 'PL'},
  {title: 'A JA WOLĘ MOJĄ MAMĘ', author: 'MAJKA JEŻOWSKA', lang: 'PL'},
  {title: 'ALIBI', author: 'MALEO REGGAE ROCKERS', lang: 'PL'},
  {title: 'BĘDZIESZ MOJĄ PANIĄ', author: 'MAREK GRECHUTA', lang: 'PL'},
  {title: 'DNI KTÓRYCH NIE ZNAMY', author: 'MAREK GRECHUTA', lang: 'PL'},
  {title: 'KOROWÓD', author: 'MAREK GRECHUTA', lang: 'PL'},
  {title: 'ALE TO JUŻ BYŁO', author: 'MARYLA RODOWICZ', lang: 'PL'},
  {title: 'KOLOROWE JARMARKI', author: 'MARYLA RODOWICZ', lang: 'PL'},
  {title: 'MAŁGOŚKA', author: 'MARYLA RODOWICZ', lang: 'PL'},
  {title: 'NIECH ŻYJE BAL', author: 'MARYLA RODOWICZ', lang: 'PL'},
  {title: 'REMEDIUM (WSIĄŚĆ DO POCIĄGU)', author: 'MARYLA RODOWICZ', lang: 'PL'},
  {title: 'TAKADUM OLD', author: 'ME MYSELF AND I', lang: 'PL'},
  {title: 'KAŻDEGO DNIA', author: 'MESAJAH', lang: 'PL'},
  {title: 'SZUKAJĄC SZCZĘŚCIA', author: 'MESAJAH FEAT. KAMIL BEDNAREK', lang: 'PL'},
  {title: 'OSTATNIA NIEDZIELA', author: 'MIECZYSŁAW FOGG', lang: 'PL'},
  {title: 'KACZUSZKA I MAK', author: 'MIECZYSŁAW WOJNICKI', lang: 'PL'},
  {title: 'MÓJ JEST TEN KAWAŁEK PODŁOGI', author: 'MR. ZOOB', lang: 'PL'},
  {title: 'JAK NIE MY TO KTO', author: 'MROZU FEAT. TOMSON', lang: 'PL'},
  {title: 'DŁUGOŚĆ DŹWIĘKU SAMOTONOŚCI', author: 'MYSLOVITZ', lang: 'PL'},
  {title: 'PEGGY BROWN', author: 'MYSLOVITZ', lang: 'PL'},
  {title: 'SCENARIUSZ DLA MOICH SĄSIADÓW', author: 'MYSLOVITZ', lang: 'PL'},
  {title: 'SPRZEDAWCY MARZEŃ', author: 'MYSLOVITZ', lang: 'PL'},
  {title: 'Z TWARZĄ MARILYN MONROE', author: 'MYSLOVITZ', lang: 'PL'},
  {title: 'KOBIETY SĄ GORĄCE', author: 'NORBI', lang: 'PL'},
  {title: 'KIEDY POWIEM SOBIE DOŚĆ', author: 'O.N.A.', lang: 'PL'},
  {title: 'NIE PYTAJ O POLSKĘ', author: 'OBYWATEL G.C.', lang: 'PL'},
  {title: 'JESTEM BOGIEM', author: 'PAKTOFONIKA', lang: 'PL'},
  {title: 'CAŁUJ MNIE', author: 'PAWEŁ KUKIZ & PIERSI', lang: 'PL'},
  {title: 'GŁUCHA NOC', author: 'PEJA', lang: 'PL'},
  {title: 'AUTOBIOGRAFIA', author: 'PERFECT', lang: 'PL'},
  {title: 'CHCEMY BYĆ SOBĄ', author: 'PERFECT', lang: 'PL'},
  {title: 'NIE PŁACZ EWKA', author: 'PERFECT', lang: 'PL'},
  {title: 'NIEWIELE CI MOGĘ DAĆ', author: 'PERFECT', lang: 'PL'},
  {title: 'TO MY POLACY', author: 'PIĘĆ DWA', lang: 'PL'},
  {title: 'BAŁKANICA', author: 'PIERSI', lang: 'PL'},
  {title: 'NIECH MÓWIĄ, ŻE TO NIE JEST MIŁOŚĆ', author: 'PIOTR RUBIK', lang: 'PL'},
  {title: 'KOCHAĆ (TO ŁATWO POWIEDZIEĆ)', author: 'PIOTR SZCZEPANIK', lang: 'PL'},
  {title: 'POCZĄTEK', author: 'PODSIADŁO, KORTEZ, ZALEWSKI', lang: 'PL'},
  {title: 'GÓRNICZO HUTNICZA ORKIESTRA DĘTA', author: 'POGODNO', lang: 'PL'},
  {title: 'BYŁAŚ DLA MNIE WSZYSTKIM', author: 'POPARZENI KAWĄ TRZY', lang: 'PL'},
  {title: 'FLARY', author: 'PRO8L3M', lang: 'PL'},
  {title: 'KIEDYŚ CIĘ ZNAJDĘ', author: 'RENI JUSIS', lang: 'PL'},
  {title: 'ZAKRECONA', author: 'RENI JUSIS', lang: 'PL'},
  {title: 'BIAŁA FLAGA', author: 'REPUBLIKA', lang: 'PL'},
  {title: 'MAMONA', author: 'REPUBLIKA', lang: 'PL'},
  {title: 'NIE STAŁO SIĘ NIC', author: 'ROBERT GAWLIŃSKI', lang: 'PL'},
  {title: 'NA JEDNEJ Z DZIKICH PLAŹ (LUBIŁA TAŃCZYĆ)', author: 'ROTARY', lang: 'PL'},
  {title: 'JEDZIE POCIĄG Z DALEKA', author: 'RYSZARD RYNKOWSKI', lang: 'PL'},
  {title: 'ŻYCIE JEST NOWELĄ (KLAN)', author: 'RYSZARD RYNKOWSKI', lang: 'PL'},
  {title: 'NAUCZ MNIE', author: 'SARSA', lang: 'PL'},
  {title: 'OTWIERAM WINO', author: 'SIDNEY POLAK', lang: 'PL'},
  {title: 'WSZYSTKO KWITNIE WKOŁO (WIOSNA)', author: 'SKALDOWIE', lang: 'PL'},
  {title: 'WSZYSTKO MI MÓWI, ŻE MNIE KTOŚ POKOCHAŁ', author: 'SKALDOWIE', lang: 'PL'},
  {title: 'Z KOPYTA KULIG RWIE', author: 'SKALDOWIE', lang: 'PL'},
  {title: 'MIŁOŚĆ W ZAKOPANEM', author: 'SŁAWOMIR', lang: 'PL'},
  {title: 'W AUCIE', author: 'SOKÓŁ FEAT. PONO, FRED & FRANEK KIMONO', lang: 'PL'},
  {title: 'DOSKO', author: 'STACHURSKY', lang: 'PL'},
  {title: 'TYP NIEPOKORNY', author: 'STACHURSKY', lang: 'PL'},
  {title: 'CZARNY BLUES O CZWARTEJ NAD RANEM', author: 'STARE DOBRE MAŁŻEŃSTWO', lang: 'PL'},
  {title: 'CZARNY CHLEB I CZARNA KAWA', author: 'STRACHY NA LACHY', lang: 'PL'},
  {title: 'DZIEŃ DOBRY, KOCHAM CIĘ', author: 'STRACHY NA LACHY', lang: 'PL'},
  {title: 'PIŁA TANGO', author: 'STRACHY NA LACHY', lang: 'PL'},
  {title: 'RAISSA', author: 'STRACHY NA LACHY', lang: 'PL'},
  {title: 'MAŁE RZECZY', author: 'SYLWIA GRZESZCZAK', lang: 'PL'},
  {title: 'CO Z NAMI BĘDZIE', author: 'SYLWIA GRZESZCZAK & LIBER', lang: 'PL'},
  {title: 'WIEŻA RADOŚCI, WIEŻA SAMOTNOŚCI', author: 'SZTYWNY PAL AZJI', lang: 'PL'},
  {title: 'U CIOCI NA IMIENINACH', author: 'SZWAGIERKOLASKA', lang: 'PL'},
  {title: 'CHŁOPAKI NIE PŁACZĄ', author: 'T.LOVE', lang: 'PL'},
  {title: 'KING', author: 'T.LOVE', lang: 'PL'},
  {title: 'NIE NIE NIE', author: 'T.LOVE', lang: 'PL'},
  {title: 'WARSZAWA', author: 'T.LOVE', lang: 'PL'},
  {title: 'DESZCZ NA BETONIE', author: 'TACO HEMINGWAY', lang: 'PL'},
  {title: 'TAMAGOTCHI', author: 'TACONAFIDE', lang: 'PL'},
  {title: 'ZEGARMISTRZ ŚWIATŁA', author: 'TADEUSZ WOŹNIAK', lang: 'PL'},
  {title: 'TAKIEGO JANICKA', author: 'TERAZMY', lang: 'PL'},
  {title: 'KOCHAM BYĆ Z TOBĄ', author: 'THE DUMPLINGS', lang: 'PL'},
  {title: '10 W SKALI BEAUFORTA', author: 'TRZY KORONY', lang: 'Szanta'},
  {title: 'DMUCHAWCE, LATAWCE WIATR', author: 'URSZULA', lang: 'PL'},
  {title: 'KONIK NA BIEGUNACH', author: 'URSZULA', lang: 'PL'},
  {title: 'ORŁA CIEŃ', author: 'VARIUS MANX', lang: 'PL'},
  {title: 'ZANIM ZROZUMIESZ (ONA MA SIŁĘ)', author: 'VARIUS MANX', lang: 'PL'},
  {title: 'JAH JEST PREZYDENTEM', author: 'VAVAMUFFIN', lang: 'PL'},
  {title: 'ŚRODA CZWARTEK', author: 'VIDEO', lang: 'PL'},
  {title: 'WSZYSTKO JEDNO', author: 'VIDEO', lang: 'PL'},
  {title: 'BANANOWY SONG', author: 'VOX', lang: 'PL'},
  {title: 'KOLEDZY', author: 'WAGLEWSKI & MALEŃCZUK', lang: 'PL'},
  {title: 'MONIKA, DZIEWCZYNA RATOWNIKA', author: 'WAŁY JAGIELLOŃSKIE', lang: 'PL'},
  {title: 'ONA TAŃCZY DLA MNIE', author: 'WEEKEND', lang: 'PL'},
  {title: 'SZCZUPAK (IDZIE NA TARŁO)', author: 'WETLINA', lang: 'PL'},
  {title: 'BAŚKA', author: 'WILKI', lang: 'PL'},
  {title: 'BOHEMA', author: 'WILKI', lang: 'PL'},
  {title: 'SON OF THE BLUE SKY', author: 'WILKI', lang: 'PL'},
  {title: 'PRZYGODA, PRZYGODA', author: 'WIŚLANIE 69', lang: 'PL'},
  {title: 'GDZIE SIE PODZIAŁY TAMTE PRYWATKI?', author: 'WOJCIECH GĄSSOWSKI', lang: 'PL'},
  {title: 'POLONEZ Z PANA TADEUSZA', author: 'WOJCIECH KILAR', lang: 'PL'},
  {title: 'MIASTO BUDZI SIĘ', author: 'YUGOPOLIS & PAWEŁ KUKIZ', lang: 'PL'},
  {title: 'OSTATNIA NOCKA', author: 'YUGOPOLIS, MACIEJ MALEŃCZUK', lang: 'PL'},
  {title: 'BOSO', author: 'ZAKOPOWER', lang: 'PL'},
  {title: 'CHAŁUPY WELCOME TO', author: 'ZBIGNIEW WODECKI', lang: 'PL'},
  {title: 'PSZCZÓŁKA MAJA', author: 'ZBIGNIEW WODECKI', lang: 'PL'},
  {title: 'BANIA U CYGANA', author: 'ZERO', lang: 'PL'},
  {title: '24 BYŁ LUTEGO', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'AMSTERDAM', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'BITWA', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'BOB BUDOWNICZY', author: '', lang: 'PL'},
  {title: 'GDZIE TA KEJA', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'HISZPAŃSKIE DZIEWCZYNY', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'MARCO POLO', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'MORSKIE OPOWIEŚCI', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'PACYFIK', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'POŻEGNANIE LIVERPOOLU', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'PRESS GANG', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'PRZECHYŁY', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'ŚMIAŁY HARPUNNIK (NASZ DIAMENT)', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'STARY BRYG', author: '(SZANTA)', lang: 'Szanta'},
  {title: 'UKRAINA (HEJ SOKOŁY)', author: '', lang: 'PL'},
  {title: 'RÓŻA I BEZ (JAK ROZPĘTAŁEM IIWŚ)', author: 'ANDRZEJ ŻARNECKI', lang: 'PL'},
  {title: 'MOTYW Z VABANK', author: '', lang: 'PL'}
]
