var songs = [
  {title: 'SANDSTORM', author: 'DARUDE', deck: 'INT'},
  {title: 'DREADLOCK HOLIDAY', author: '10CC', deck: 'INT'},
  {title: 'TAKE ON ME', author: 'A-HA', deck: 'INT'},
  {title: 'DANCING QUEEN', author: 'ABBA', deck: 'INT'},
  {title: 'GIMME! GIMME! GIMME!', author: 'ABBA', deck: 'INT'},
  {title: 'MAMMA MIA', author: 'ABBA', deck: 'INT'},
  {title: 'BACK IN BLACK', author: 'AC/DC', deck: 'INT'},
  {title: 'HIGHWAY TO HELL', author: 'AC/DC', deck: 'INT'},
  {title: 'ROLLING IN THE DEEP', author: 'ADELE', deck: 'INT'},
  {title: 'SKYFALL', author: 'ADELE', deck: 'INT'},
  {title: 'SOMEONE LIKE YOU', author: 'ADELE', deck: 'INT'},
  {title: 'ADIEMUS', author: 'ADIEMUS', deck: 'INT'},
  {title: 'DREAM ON', author: 'AEROSMITH', deck: 'INT'},
  {title: 'I DON\'T WANT TO MISS A THING', author: 'AEROSMITH', deck: 'INT'},
  {title: 'KEELHAULED', author: 'ALESTORM', deck: 'INT'},
  {title: 'FOREVER YOUNG', author: 'ALPHAVILLE', deck: 'INT'},
  {title: 'BREEZEBLOCKS', author: 'ALT-J', deck: 'INT'},
  {title: 'ENIGMA (GIVE A BIT OF MMM TO ME)', author: 'AMANDA LEAR', deck: 'INT'},
  {title: 'A HORSE WITH NO NAME', author: 'AMERICA', deck: 'INT'},
  {title: 'REHAB', author: 'AMY WINEHOUSE', deck: 'INT'},
  {title: 'TIME TO SAY GOODBYE', author: 'ANDREA BOCELLI, SARAH BRIGHTMAN', deck: 'INT'},
  {title: 'FOUR SEASONS, SPRING', author: 'ANTIONIO VIVALDI', deck: 'INT'},
  {title: 'CANCION DEL MARIACHI', author: 'ANTONIO BANDERAS, LOS LOBOS', deck: 'INT'},
  {title: 'BARBIE GIRL', author: 'AQUA', deck: 'INT'},
  {title: 'AGAIN', author: 'ARCHIVE', deck: 'INT'},
  {title: 'DO I WANNA KNOW?', author: 'ARCTIC MONKEYS', deck: 'INT'},
  {title: 'RESPECT', author: 'ARETHA FRANKLIN', deck: 'INT'},
  {title: 'THINK', author: 'ARETHA FRANKLIN', deck: 'INT'},
  {title: 'HEY BROTHER', author: 'AVICII', deck: 'INT'},
  {title: 'WAKE ME UP', author: 'AVICII', deck: 'INT'},
  {title: 'EVERYBODY', author: 'BACKSTREET BOYS', deck: 'INT'},
  {title: 'WHO LET THE DOGS OUT', author: 'BAHA MEN', deck: 'INT'},
  {title: 'WOMAN IN LOVE', author: 'BARBRA STREISAND', deck: 'INT'},
  {title: 'GOOD VIBRATIONS', author: 'BEACH BOYS', deck: 'INT'},
  {title: 'I GET AROUND', author: 'BEACH BOYS', deck: 'INT'},
  {title: 'HOW DEEP IS YOUR LOVE', author: 'BEE GEES', deck: 'INT'},
  {title: 'STAYIN\' ALIVE', author: 'BEE GEES', deck: 'INT'},
  {title: 'STAND BY ME', author: 'BEN E. KING', deck: 'INT'},
  {title: 'HALO', author: 'BEYONCÉ', deck: 'INT'},
  {title: 'ROCK AROUND THE CLOCK', author: 'BILL HALEY', deck: 'INT'},
  {title: 'HOOKED ON A FEELING', author: 'BJÖRN SKIFS', deck: 'INT'},
  {title: 'I GOTTA FEELING', author: 'BLACK EYED PEAS', deck: 'INT'},
  {title: 'WHERE IS THE LOVE?', author: 'BLACK EYED PEAS', deck: 'INT'},
  {title: 'IRON MAN', author: 'BLACK SABBATH', deck: 'INT'},
  {title: 'PARANOID', author: 'BLACK SABBATH', deck: 'INT'},
  {title: 'ALL THE SMALL THINGS', author: 'BLINK-182', deck: 'INT'},
  {title: 'CALL ME', author: 'BLONDIE', deck: 'INT'},
  {title: 'MARIA', author: 'BLONDIE', deck: 'INT'},
  {title: 'THE BAD TOUCH', author: 'BLOODHOUND GANG', deck: 'INT'},
  {title: 'SONG 2', author: 'BLUR', deck: 'INT'},
  {title: 'BLOWIN\' IN THE WIND', author: 'BOB DYLAN', deck: 'INT'},
  {title: 'KNOCKIN\' ON HEAVEN\'S DOOR', author: 'BOB DYLAN', deck: 'INT'},
  {title: 'LIKE A ROLLING STONE', author: 'BOB DYLAN', deck: 'INT'},
  {title: 'I SHOT THE SHERIFF', author: 'BOB MARLEY', deck: 'INT'},
  {title: 'NO WOMAN NO CRY', author: 'BOB MARLEY', deck: 'INT'},
  {title: 'DON\'T WORRY BE HAPPY', author: 'BOBBY MCFERRIN', deck: 'INT'},
  {title: 'IT\'S MY LIFE', author: 'BON JOVI', deck: 'INT'},
  {title: 'LIVIN\' ON A PRAYER', author: 'BON JOVI', deck: 'INT'},
  {title: 'DADDY COOL', author: 'BONEY M', deck: 'INT'},
  {title: 'RASPUTIN', author: 'BONEY M', deck: 'INT'},
  {title: 'HOLDING OUT FOR A HERO', author: 'BOONIE TYLER', deck: 'INT'},
  {title: 'TOTAL ECLIPSE OF THE HEART', author: 'BOONIE TYLER', deck: 'INT'},
  {title: 'MORE THAN A FEELING', author: 'BOSTON', deck: 'INT'},
  {title: '... BABY ONE MORE TIME', author: 'BRITNEY SPEARS', deck: 'INT'},
  {title: 'OOPS!... I DID IT AGAIN', author: 'BRITNEY SPEARS', deck: 'INT'},
  {title: 'TOXIC', author: 'BRITNEY SPEARS', deck: 'INT'},
  {title: 'BORN IN THE U.S.A.', author: 'BRUCE SPRINGSTEEN', deck: 'INT'},
  {title: 'CALL ME MAYBE', author: 'CARLY RAE JEPSEN', deck: 'INT'},
  {title: 'MY HEART WILL GO ON', author: 'CELINE DION', deck: 'INT'},
  {title: 'BELIEVE', author: 'CHER', deck: 'INT'},
  {title: 'THE SHOOP SHOOP SONG', author: 'CHER', deck: 'INT'},
  {title: 'LET\'S TWIST AGAIN', author: 'CHUBBY CHECKER', deck: 'INT'},
  {title: 'JOHNNY B. GOOD', author: 'CHUCK BERRY', deck: 'INT'},
  {title: 'HYMN FOR THE WEEKEND', author: 'COLDPLAY', deck: 'INT'},
  {title: 'VIVA LA VIDA', author: 'COLDPLAY', deck: 'INT'},
  {title: 'YELLOW', author: 'COLDPLAY', deck: 'INT'},
  {title: 'GANGSTA\'S PARADISE', author: 'COOLIO', deck: 'INT'},
  {title: 'SUNSHINE OF YOUR LOVE', author: 'CREAM', deck: 'INT'},
  {title: 'FORTUNATE SON', author: 'CREEDENCE CLEARWATER REVIVAL', deck: 'INT'},
  {title: 'SUZY Q', author: 'CREEDENCE CLEARWATER REVIVAL', deck: 'INT'},
  {title: 'HAVE YOU EVER SEEN THE RAIN?', author: 'CREEDENCE CLEARWATER REVIVAL', deck: 'INT'},
  {title: 'DO YOU REALLY WANT TO HURT ME', author: 'CULTURE CLUB', deck: 'INT'},
  {title: 'KARMA CHAMELEON', author: 'CULTURE CLUB', deck: 'INT'},
  {title: '(I JUST) DIED IN YOUR ARMS', author: 'CUTTING CREW', deck: 'INT'},
  {title: 'GIRLS JUST WANT TO HAVE FUN', author: 'CYNDI LAUPER', deck: 'INT'},
  {title: 'TIME AFTER TIME', author: 'CYNDI LAUPER', deck: 'INT'},
  {title: 'GET LUCKY', author: 'DAFT PUNK', deck: 'INT'},
  {title: 'LET\'S DANCE', author: 'DAVID BOWIE', deck: 'INT'},
  {title: 'LIFE ON MARS?', author: 'DAVID BOWIE', deck: 'INT'},
  {title: 'SPACE ODDITY', author: 'DAVID BOWIE', deck: 'INT'},
  {title: 'BREAKFAST AT TIFFANY\'S', author: 'DEEP BLUE SOMETHING', deck: 'INT'},
  {title: 'CHILD IN TIME', author: 'DEEP PURPLE', deck: 'INT'},
  {title: 'SMOKE ON THE WATER', author: 'DEEP PURPLE', deck: 'INT'},
  {title: 'ENJOY THE SILENCE', author: 'DEPECHE MODE', deck: 'INT'},
  {title: 'PERSONAL JESUS', author: 'DEPECHE MODE', deck: 'INT'},
  {title: 'VOYAGE, VOYAGE', author: 'DESIRELESS', deck: 'INT'},
  {title: 'MISIRLOU (PULP FICTION OPENING)', author: 'DICK DALE', deck: 'INT'},
  {title: 'BROTHERS IN ARMS', author: 'DIRE STRAITS', deck: 'INT'},
  {title: 'SULTANS OF SWING', author: 'DIRE STRAITS', deck: 'INT'},
  {title: 'JOLENE', author: 'DOLLY PARTON', deck: 'INT'},
  {title: 'AMERICAN PIE', author: 'DON MCLEAN', deck: 'INT'},
  {title: 'I\'M SHIPPING UP TO BOSTON', author: 'DROPKICK MURPHYS', deck: 'INT'},
  {title: 'ROSE TATTO', author: 'DROPKICK MURPHYS', deck: 'INT'},
  {title: 'BARBRA STREISAND', author: 'DUCK SAUCE', deck: 'INT'},
  {title: 'SON OF A PREACHER MAN', author: 'DUSTY SPRINGFIELD', deck: 'INT'},
  {title: 'HOTEL CALIFORNIA', author: 'EAGLES', deck: 'INT'},
  {title: 'I SEE FIRE', author: 'ED SHEERAN', deck: 'INT'},
  {title: 'SHAPE OF YOU', author: 'ED SHEERAN', deck: 'INT'},
  {title: 'THINKING OUT LOUD', author: 'ED SHEERAN', deck: 'INT'},
  {title: 'EVENING OVER ROOFTOPS', author: 'EDGAR BROUGHTON BAND', deck: 'INT'},
  {title: 'NON, JE NE REGRETTE RIEN', author: 'EDITH PIAF', deck: 'INT'},
  {title: 'IN THE HALL OF THE MOUNTAIN KING', author: 'EDVARD GRIEG', deck: 'INT'},
  {title: 'HOME', author: 'EDWARD SHARPE & THE MAGNETIC ZEROS', deck: 'INT'},
  {title: 'I\'M BLUE', author: 'EIFFEL 65', deck: 'INT'},
  {title: 'MR. BLUE SKY', author: 'ELECTRIC LIGHT ORCHESTRA', deck: 'INT'},
  {title: 'CAN YOU FEEL THE LOVE TONIGHT', author: 'ELTON JOHN', deck: 'INT'},
  {title: 'I\'M STILL STANDING', author: 'ELTON JOHN', deck: 'INT'},
  {title: 'BLUE SUEDE SHOES', author: 'ELVIS PRESLEY', deck: 'INT'},
  {title: 'CAN\'T HELP FALLING IN LOVE', author: 'ELVIS PRESLEY', deck: 'INT'},
  {title: 'JAILHOUSE ROCK', author: 'ELVIS PRESLEY', deck: 'INT'},
  {title: 'LOSE YOURSELF', author: 'EMINEM', deck: 'INT'},
  {title: 'WITHOUT ME', author: 'EMINEM', deck: 'INT'},
  {title: 'BAILANDO', author: 'ENRIQUE IGLESIAS', deck: 'INT'},
  {title: 'ORINOCO FLOW', author: 'ENYA', deck: 'INT'},
  {title: 'LAYLA', author: 'ERIC CLAPTON', deck: 'INT'},
  {title: 'TEARS IN HEAVEN', author: 'ERIC CLAPTON', deck: 'INT'},
  {title: 'SWEET DREAMS', author: 'EURITHMICS', deck: 'INT'},
  {title: 'THE FINAL COUNTDOWN', author: 'EUROPE', deck: 'INT'},
  {title: 'BRING ME TO LIFE', author: 'EVANESCENCE', deck: 'INT'},
  {title: 'DREAMS', author: 'FLEETWOOD MAC', deck: 'INT'},
  {title: 'LITTLE LIES', author: 'FLEETWOOD MAC', deck: 'INT'},
  {title: 'WHISTLE', author: 'FLO RIDA', deck: 'INT'},
  {title: 'NO LIGHT, NO LIGHT', author: 'FLORENCE + THE MACHINE', deck: 'INT'},
  {title: 'TOCA TOCA', author: 'FLY PROJECT', deck: 'INT'},
  {title: 'LEMON TREE', author: 'FOOL\'S GARDEN', deck: 'INT'},
  {title: 'PUMPED UP KICKS', author: 'FOSTER THE PEOPLE', deck: 'INT'},
  {title: 'OCCIDENTALI\'S KARMA', author: 'FRANCESCO GABBANI', deck: 'INT'},
  {title: 'SOMETHING STUPID', author: 'FRANK & NANCY SINATRA', deck: 'INT'},
  {title: 'STRANGERS IN THE NIGHT', author: 'FRANK SINATRA', deck: 'INT'},
  {title: 'MY WAY', author: 'FRANK SINATRA', deck: 'INT'},
  {title: 'CAN\'T TAKE MY EYES OFF YOU', author: 'FRANKIE VALLI', deck: 'INT'},
  {title: 'FIRE', author: 'FRANZ FERDINAND', deck: 'INT'},
  {title: 'TAKE ME OUT', author: 'FRANZ FERDINAND', deck: 'INT'},
  {title: 'WALK AWAY', author: 'FRANZ FERDINAND', deck: 'INT'},
  {title: 'MAD WORLD', author: 'GARY JULES', deck: 'INT'},
  {title: 'SINGIN\' IN THE RAIN', author: 'GENE KELLY', deck: 'INT'},
  {title: 'MAMA', author: 'GENESIS', deck: 'INT'},
  {title: 'CARELESS WISPER (I\'M NEVER GONNA DANCE AGAIN)', author: 'GEORGE MICHAEL', deck: 'INT'},
  {title: 'BAKER STREET', author: 'GERRY RAFFERTY', deck: 'INT'},
  {title: 'THE RIDDLE', author: 'GIGI D\'AGOSTINO', deck: 'INT'},
  {title: 'I WILL SURVIVE', author: 'GLORIA GAYNOR', deck: 'INT'},
  {title: 'CRAZY', author: 'GNARLS BARKLEY', deck: 'INT'},
  {title: 'KALASHNIKOV', author: 'GORAN BREGOVIC', deck: 'INT'},
  {title: 'FEEL GOOD INC.', author: 'GORILLAZ', deck: 'INT'},
  {title: 'SOMEBODY THAT I USED TO KNOW', author: 'GOTYE', deck: 'INT'},
  {title: 'BOULEVARD OF BROKEN DREAMS', author: 'GREEN DAY', deck: 'INT'},
  {title: 'NOVEMBER RAIN', author: 'GUNS\'N\'ROSES', deck: 'INT'},
  {title: 'PARADISE CITY', author: 'GUNS\'N\'ROSES', deck: 'INT'},
  {title: 'SWEET CHILD OF MINE', author: 'GUNS\'N\'ROSES', deck: 'INT'},
  {title: 'WELCOME TO THE JUNGLE', author: 'GUNS\'N\'ROSES', deck: 'INT'},
  {title: 'WHAT IS LOVE? (BABY DON\'T HURT ME)', author: 'HADDAWAY', deck: 'INT'},
  {title: 'OVER THE RAINBOW', author: 'JUDY GARLAND / ISRAEL KAMAKAWIWOʻOLE', deck: 'INT'},
  {title: 'TAKE ME TO CHURCH', author: 'HOZIER', deck: 'INT'},
  {title: 'LUST FOR LIFE', author: 'IGGY POP', deck: 'INT'},
  {title: 'THE PASSENGER', author: 'IGGY POP', deck: 'INT'},
  {title: 'BELIEVER', author: 'IMAGINE DRAGONS', deck: 'INT'},
  {title: 'RADIOACTIVE', author: 'IMAGINE DRAGONS', deck: 'INT'},
  {title: 'LET IT GO (FROM FROZEN)', author: 'INDINA MENZEL', deck: 'INT'},
  {title: 'JOHNNY I HARDLY KNEW YOU', author: 'IRISH ROVERS', deck: 'INT'},
  {title: 'IN-A-GADDA-DA-VIDA', author: 'IRON BUTTERFLY', deck: 'INT'},
  {title: 'FEAR OF THE DARK', author: 'IRON MAIDEN', deck: 'INT'},
  {title: 'YOU\'RE BEAUTIFUL', author: 'JAMES BLUNT', deck: 'INT'},
  {title: 'I FEEL GOOD', author: 'JAMES BROWN', deck: 'INT'},
  {title: 'THIS IS A MEN\'S WORLD', author: 'JAMES BROWN', deck: 'INT'},
  {title: 'TOCCATA AND FUGUE IN D MINOR', author: 'JAN S. BACH', deck: 'INT'},
  {title: '(TAKE ANOTHER) PIECE OF MY HEART', author: 'JANIS JOPLIN', deck: 'INT'},
  {title: 'I\'M YOURS', author: 'JASON MARZ', deck: 'INT'},
  {title: 'SOMEBODY TO LOVE', author: 'JEFFERSON\'S AIRPLANE', deck: 'INT'},
  {title: 'WHITE RABBIT', author: 'JEFFERSON\'S AIRPLANE', deck: 'INT'},
  {title: 'LET\'S GET LOUD', author: 'JENNIFER LOPEZ', deck: 'INT'},
  {title: 'ARE YOU GONNA BE MY GIRL', author: 'JET', deck: 'INT'},
  {title: 'ALL ALONG THE WATCHTOWER', author: 'JIMI HENDRIX', deck: 'INT'},
  {title: 'HEY JOE', author: 'JIMI HENDRIX', deck: 'INT'},
  {title: 'I LOVE ROCK \'N\' ROLL', author: 'JOAN JETT & THE BLACKHEARTS', deck: 'INT'},
  {title: 'WITH A LITTLE HELP FROM MY FRIENDS', author: 'JOE COCKER', deck: 'INT'},
  {title: 'LES CHAMPS ELYSEES', author: 'JOE DASSIN', deck: 'INT'},
  {title: 'COUNTRY ROADS', author: 'JOHN DENVER', deck: 'INT'},
  {title: 'IMAGINE', author: 'JOHN LENNON', deck: 'INT'},
  {title: 'SUMMER NIGHTS (FROM GREASE)', author: 'JOHN TRAVOLTA & OLIVIA NEWTON-JOHN', deck: 'INT'},
  {title: 'YOU\'RE THE ONE THAT I WANT (FROM GREASE)', author: 'JOHN TRAVOLTA & OLIVIA NEWTON-JOHN', deck: 'INT'},
  {title: 'I WALK THE LINE', author: 'JOHNNY CASH', deck: 'INT'},
  {title: 'DON\'T STOP BELIEVIN\'', author: 'JOURNEY', deck: 'INT'},
  {title: 'LA CAMISA NEGRA', author: 'JUANES', deck: 'INT'},
  {title: 'COLORS OF THE WIND (POCAHONTAS)', author: 'JUDY KUHN', deck: 'INT'},
  {title: 'RUBY', author: 'KAISER CHIEFS', deck: 'INT'},
  {title: 'DUST IN THE WIND', author: 'KANSAS', deck: 'INT'},
  {title: 'NINE MILLION BICYCLES', author: 'KATIE MELUA', deck: 'INT'},
  {title: 'HOT N COLD', author: 'KATY PERRY', deck: 'INT'},
  {title: 'I KISSED A GIRL', author: 'KATY PERRY', deck: 'INT'},
  {title: 'ROAR', author: 'KATY PERRY', deck: 'INT'},
  {title: 'NIGHTCALL (FROM DRIVE)', author: 'KAVINSKY', deck: 'INT'},
  {title: 'TIK TOK', author: 'KESHA', deck: 'INT'},
  {title: 'EPITAPH', author: 'KING CRIMSON', deck: 'INT'},
  {title: 'THE COURT OF THE CRIMSON KING', author: 'KING CRIMSON', deck: 'INT'},
  {title: 'SEX ON FIRE', author: 'KINGS OF LEON', deck: 'INT'},
  {title: 'COME WITH ME NOW', author: 'KONGOS', deck: 'INT'},
  {title: 'ALEJANDRO', author: 'LADY GAGA', deck: 'INT'},
  {title: 'BAD ROMANCE', author: 'LADY GAGA', deck: 'INT'},
  {title: 'POKER FACE', author: 'LADY GAGA', deck: 'INT'},
  {title: '\'T SMIDJE (BELGIJKA)', author: 'LAÏS', deck: 'INT'},
  {title: 'YOUNG AND BEAUTIFUL', author: 'LANA DEL REY', deck: 'INT'},
  {title: 'ASEREJÉ', author: 'LAS KETCHUP', deck: 'INT'},
  {title: 'IMMIGRANT SONG', author: 'LED ZEPPELIN', deck: 'INT'},
  {title: 'STAIRWAY TO HEAVEN', author: 'LED ZEPPELIN', deck: 'INT'},
  {title: 'WHOLE LOTTA LOVE', author: 'LED ZEPPELIN', deck: 'INT'},
  {title: 'FLY AWAY', author: 'LENNY KRAVITZ', deck: 'INT'},
  {title: 'HALLELUJAH', author: 'LEONARD COHEN', deck: 'INT'},
  {title: 'NUMB', author: 'LINKIN PARK', deck: 'INT'},
  {title: 'SAY YOU, SAY ME', author: 'LIONEL RICHIE', deck: 'INT'},
  {title: 'NARCOTIC', author: 'LIQUIDO', deck: 'INT'},
  {title: 'PARTY ROCK ANTHEM', author: 'LMFAO', deck: 'INT'},
  {title: 'MACARENA', author: 'LOS DEL RIO', deck: 'INT'},
  {title: 'WHAT A WONDERFUL WORLD', author: 'LOUIS ARMSTRONG', deck: 'INT'},
  {title: 'FÜR ELISE', author: 'LUDWIG VAN BEETHOVEN', deck: 'INT'},
  {title: 'DESPACITO', author: 'LUIS FONSI', deck: 'INT'},
  {title: 'SWEET HOME ALABAMA', author: 'LYNYRD SKYNYRD', deck: 'INT'},
  {title: 'CAN\'T HOLD US', author: 'MACKLEMORE', deck: 'INT'},
  {title: 'THRIFT SHOP', author: 'MACKLEMORE', deck: 'INT'},
  {title: 'OUR HOUSE', author: 'MADNESS', deck: 'INT'},
  {title: 'LIKE A VIRGIN', author: 'MADONNA', deck: 'INT'},
  {title: 'MATERIAL GIRL', author: 'MADONNA', deck: 'INT'},
  {title: 'LEAN ON', author: 'MAJOR LAZER', deck: 'INT'},
  {title: 'MOVES LIKE JAGGER', author: 'MAROON 5', deck: 'INT'},
  {title: 'SUGAR', author: 'MAROON 5', deck: 'INT'},
  {title: 'THIS LOVE', author: 'MAROON 5', deck: 'INT'},
  {title: 'ENTER SANDMAN', author: 'METALLICA', deck: 'INT'},
  {title: 'NOTHING ELSE MATTERS', author: 'METALLICA', deck: 'INT'},
  {title: 'KIDS', author: 'MGMT', deck: 'INT'},
  {title: 'BEAT IT', author: 'MICHAEL JACKSON', deck: 'INT'},
  {title: 'BILLIE JEAN', author: 'MICHAEL JACKSON', deck: 'INT'},
  {title: 'SMOOTH CRILIMAL', author: 'MICHAEL JACKSON', deck: 'INT'},
  {title: 'THRILLER', author: 'MICHAEL JACKSON', deck: 'INT'},
  {title: 'AI SE EU TE PEGO', author: 'MICHEL TELÓ', deck: 'INT'},
  {title: 'RELAX, TAKE IT EASY', author: 'MIKA', deck: 'INT'},
  {title: 'ALWAYS LOOK ON THE BRIGHT SIDE OF LIFE', author: 'MONTY PYTHON', deck: 'INT'},
  {title: 'THE CAVE', author: 'MUMFORD & SONS', deck: 'INT'},
  {title: 'SUPERMASSIVE BLACK HOLE', author: 'MUSE', deck: 'INT'},
  {title: 'BANG BANG (MY BABY SHOT ME DOWN)', author: 'NANCY SINATRA', deck: 'INT'},
  {title: 'THESE BOOTS ARE MADE FOR WALKIN\'', author: 'NANCY SINATRA', deck: 'INT'},
  {title: 'SUMMER WINE', author: 'NANCY SINATRA & LEE HAZLEWOOD', deck: 'INT'},
  {title: 'HOW YOU REMIND ME', author: 'NICKELBACK', deck: 'INT'},
  {title: 'FEELING GOOD', author: 'NINA SIMONE / MICHAEL BUBLÉ', deck: 'INT'},
  {title: 'COME AS YOU ARE', author: 'NIRVANA', deck: 'INT'},
  {title: 'SMELLS LIKE TEEN SPRIT', author: 'NIRVANA', deck: 'INT'},
  {title: 'DON\'T SPEAK', author: 'NO DOUBT', deck: 'INT'},
  {title: 'JUST A GIRL', author: 'NO DOUBT', deck: 'INT'},
  {title: 'DRAGOSTEA DIN TEI (NUMA NUMA JEJ)', author: 'O-ZONE', deck: 'INT'},
  {title: 'WONDERWALL', author: 'OASIS', deck: 'INT'},
  {title: 'DIRTY PAWS', author: 'OF MONSTERS AND MEN', deck: 'INT'},
  {title: 'GYONGYHAJU LANY (THE GIRL WITH PEARLY HAIR)', author: 'OMEGA', deck: 'INT'},
  {title: 'COUNTING STARS', author: 'ONEREPUBLIC', deck: 'INT'},
  {title: 'BOOTY SWING', author: 'PAROV STELAR', deck: 'INT'},
  {title: 'LET HER GO', author: 'PASSENGER', deck: 'INT'},
  {title: 'BECAUSE THE NIGHT', author: 'PATTI SMITH', deck: 'INT'},
  {title: 'ALIVE', author: 'PEARL JAM', deck: 'INT'},
  {title: 'ALWAYS ON MY MIND', author: 'PET SHOP BOYS', deck: 'INT'},
  {title: 'HAPPY', author: 'PHARRELL WILLIAMS', deck: 'INT'},
  {title: 'ANOTHER DAY IN PARADISE', author: 'PHIL COLLINS', deck: 'INT'},
  {title: 'ANOTHER BRICK IN THE WALL', author: 'PINK FLOYD', deck: 'INT'},
  {title: 'HEY YOU', author: 'PINK FLOYD', deck: 'INT'},
  {title: 'HIGH HOPES', author: 'PINK FLOYD', deck: 'INT'},
  {title: 'MONEY', author: 'PINK FLOYD', deck: 'INT'},
  {title: 'SHINE ON YOU CRAZY DIAMOND', author: 'PINK FLOYD', deck: 'INT'},
  {title: 'WISH YOU WERE HERE', author: 'PINK FLOYD', deck: 'INT'},
  {title: 'TIMBER', author: 'PITBULL', deck: 'INT'},
  {title: 'WHERE IS MY MIND?', author: 'PIXIES', deck: 'INT'},
  {title: 'PURPLE RAIN', author: 'PRINCE', deck: 'INT'},
  {title: 'GANGAM STYLE', author: 'PSY', deck: 'INT'},
  {title: 'BOHEMIAN RHAPSODY', author: 'QUEEN', deck: 'INT'},
  {title: 'DON\'T STOP ME NOW', author: 'QUEEN', deck: 'INT'},
  {title: 'RADIO GAGA', author: 'QUEEN', deck: 'INT'},
  {title: 'THE SHOW MUST GO ON', author: 'QUEEN', deck: 'INT'},
  {title: 'WE ARE THE CHAMPIONS', author: 'QUEEN', deck: 'INT'},
  {title: 'WE WILL ROCK YOU', author: 'QUEEN', deck: 'INT'},
  {title: 'I BELIEVE I CAN FLY', author: 'R. KELLY', deck: 'INT'},
  {title: 'EVERYBODY HURTS', author: 'R.E.M.', deck: 'INT'},
  {title: 'IT\'S THE END OF THE WORLD THAT WE KNOW IT', author: 'R.E.M.', deck: 'INT'},
  {title: 'LOSING MY RELIGION', author: 'R.E.M.', deck: 'INT'},
  {title: 'CREEP', author: 'RADIOHEAD', deck: 'INT'},
  {title: 'KARMA POLICE', author: 'RADIOHEAD', deck: 'INT'},
  {title: 'HIT THE ROAD JACK', author: 'RAY CHARLES', deck: 'INT'},
  {title: 'FOR AMERICA', author: 'RED BOX', deck: 'INT'},
  {title: 'CALIFORNICATION', author: 'RED HOT CHILI PEPPERS', deck: 'INT'},
  {title: 'OTHERSIDE', author: 'RED HOT CHILI PEPPERS', deck: 'INT'},
  {title: 'SNOW (HEY OH)', author: 'RED HOT CHILI PEPPERS', deck: 'INT'},
  {title: 'UNDER THE BRIDGE', author: 'RED HOT CHILI PEPPERS', deck: 'INT'},
  {title: 'DANI CALIFORNIA', author: 'RED HOT CHILI PEPPERS', deck: 'INT'},
  {title: 'NEVER GONNA GIVE YOU UP', author: 'RICK ASTLEY', deck: 'INT'},
  {title: 'UMBRELLA', author: 'RIHANNA', deck: 'INT'},
  {title: 'LA BAMBA', author: 'RITCHIE VALENS', deck: 'INT'},
  {title: 'BLURRED LINES', author: 'ROBIN THICKE, PHARRELL WILLIAMS & T.I.', deck: 'INT'},
  {title: 'LISTEN TO YOUR HEART', author: 'ROXETTE', deck: 'INT'},
  {title: 'OH, PRETTY WOMAN', author: 'ROY ORBISON', deck: 'INT'},
  {title: 'DA COCONUT NUT (COCONUT SONG)', author: 'RYAN CAYABYAB', deck: 'INT'},
  {title: 'SMOOTH', author: 'SANTANA & ROB THOMAS', deck: 'INT'},
  {title: 'WIND OF CHANGE', author: 'SCORPIONS', deck: 'INT'},
  {title: '(IF YOU\'RE GOING TO) SAN FRANSISCO', author: 'SCOTT MCKENZIE', deck: 'INT'},
  {title: 'HIPS DON\'T LIE', author: 'SHAKIRA', deck: 'INT'},
  {title: 'WAKA WAKA (THIS TIME FOR AFRICA)', author: 'SHAKIRA', deck: 'INT'},
  {title: 'WHENEVER, WHEREVER', author: 'SHAKIRA', deck: 'INT'},
  {title: 'SEÑORITA', author: 'SHAWN MENDES, CAMILA CABELLO', deck: 'INT'},
  {title: 'MRS ROBINSON', author: 'SIMON & GARFUNKEL', deck: 'INT'},
  {title: 'THE SOUND OF SILENCE', author: 'SIMON & GARFUNKEL', deck: 'INT'},
  {title: 'ALL STAR', author: 'SMASH MOUTH', deck: 'INT'},
  {title: 'BLACK HOLE SUN', author: 'SOUNDGARDEN', deck: 'INT'},
  {title: 'WANNABE', author: 'SPICE GIRLS', deck: 'INT'},
  {title: 'BORN TO BE WILD', author: 'STEPPENWOLF', deck: 'INT'},
  {title: 'ENGLISHMAN IN NEW YORK', author: 'STING', deck: 'INT'},
  {title: 'FIELDS OF GOLD', author: 'STING', deck: 'INT'},
  {title: 'SHAPE OF MY HEART', author: 'STING', deck: 'INT'},
  {title: 'LONELY DAY', author: 'SYSTEM OF A DOWN', deck: 'INT'},
  {title: 'IT FEELS LIKE I\'M ONLY GOING BACKWARDS', author: 'TAME IMPALA', deck: 'INT'},
  {title: 'NAS NE DOGONYAT', author: 'TATU', deck: 'INT'},
  {title: 'SHAKE IT OFF', author: 'TAYLOR SWIFT', deck: 'INT'},
  {title: 'SHOUT', author: 'TEARS FOR FEARS', deck: 'INT'},
  {title: 'BEELZEBOSS', author: 'TENACIOUS D', deck: 'INT'},
  {title: 'KICKAPOO', author: 'TENACIOUS D', deck: 'INT'},
  {title: 'THE HOUSE OF THE RISING SUN', author: 'THE ANIMALS', deck: 'INT'},
  {title: 'HEY JUDE', author: 'THE BEATLES', deck: 'INT'},
  {title: 'LET IT BE', author: 'THE BEATLES', deck: 'INT'},
  {title: 'YELLOW SUBMARINE', author: 'THE BEATLES', deck: 'INT'},
  {title: 'YESTERDAY', author: 'THE BEATLES', deck: 'INT'},
  {title: 'LONELY BOY', author: 'THE BLACK KEYS', deck: 'INT'},
  {title: 'VIDEO KILLED THE RADIO STA', author: 'THE BUGGLES ', deck: 'INT'},
  {title: 'TEQUILA', author: 'THE CHAMPS', deck: 'INT'},
  {title: 'MR. SANDMAN', author: 'THE CHORDETTES', deck: 'INT'},
  {title: 'ZOMBIE', author: 'THE CRANBERRIES', deck: 'INT'},
  {title: 'FRIDAY I\'M IN LOVE', author: 'THE CURE', deck: 'INT'},
  {title: 'LIGHT MY FIRE', author: 'THE DOORS', deck: 'INT'},
  {title: 'PEOPLE ARE STRANGE', author: 'THE DOORS', deck: 'INT'},
  {title: 'RIDERS ON THE STORM', author: 'THE DOORS', deck: 'INT'},
  {title: 'IRIS', author: 'THE GOO GOO DALLS', deck: 'INT'},
  {title: 'I WANT YOU BACK', author: 'THE JACKSON 5', deck: 'INT'},
  {title: 'YOU REALLY GOT ME', author: 'THE KINKS', deck: 'INT'},
  {title: 'MY SHARONA', author: 'THE KNACK', deck: 'INT'},
  {title: 'BAD HABIT', author: 'THE KOOKS', deck: 'INT'},
  {title: 'CALIFORNIA DREAMIN\'', author: 'THE MAMAS AND THE PAPAS', deck: 'INT'},
  {title: 'I\'M A BELIEVER', author: 'THE MONKEES', deck: 'INT'},
  {title: 'NIGHTS IN WHITE SATIN', author: 'THE MOODY BLUES', deck: 'INT'},
  {title: 'PRETTY FLY (FOR A WHITE GUY)', author: 'THE OFFSPRING', deck: 'INT'},
  {title: 'YOU\'RE GONNA GO FAR, KID', author: 'THE OFFSPRING', deck: 'INT'},
  {title: 'EVERY BREATH YOU TAKE', author: 'THE POLICE', deck: 'INT'},
  {title: 'ROXANNE', author: 'THE POLICE', deck: 'INT'},
  {title: 'I\'M GONNA BE (500 MILES)', author: 'THE PROCLAIMERS', deck: 'INT'},
  {title: 'FIRESTARTER', author: 'THE PRODIGY', deck: 'INT'},
  {title: 'I\'LL BE THERE FOR YOU', author: 'THE REMBRANDTS', deck: 'INT'},
  {title: '(I CAN\'T GET NO) SATISFACTION', author: 'THE ROLLING STONES', deck: 'INT'},
  {title: 'GIMME SHELTER', author: 'THE ROLLING STONES', deck: 'INT'},
  {title: 'PAINT IT BLACK', author: 'THE ROLLING STONES', deck: 'INT'},
  {title: 'ANGIE', author: 'THE ROLLING STONES', deck: 'INT'},
  {title: 'SUGAR BABY LOVE', author: 'THE RUBETTES', deck: 'INT'},
  {title: 'WILD THING', author: 'THE TROGGS', deck: 'INT'},
  {title: 'HAPPY TOGETHER', author: 'THE TURTLES', deck: 'INT'},
  {title: 'BITTER-SWEET SYMPHONY', author: 'THE VERVE', deck: 'INT'},
  {title: 'SEVEN NATION ARMY', author: 'THE WHITE STRIPES', deck: 'INT'},
  {title: 'BABA O\'RILEY', author: 'THE WHO', deck: 'INT'},
  {title: 'MY GENERATION', author: 'THE WHO', deck: 'INT'},
  {title: 'INTRO', author: 'THE XX', deck: 'INT'},
  {title: 'HAKUNA MATATA', author: 'TIM RICE & ELTON JOHN', deck: 'INT'},
  {title: 'THE BEST', author: 'TINA TURNER', deck: 'INT'},
  {title: 'GOLDENEYE', author: 'TINA TURNER', deck: 'INT'},
  {title: 'WHAT\'S LOVE GOT TO DO WITH IT', author: 'TINA TURNER', deck: 'INT'},
  {title: 'THE LION SLEEPS TONIGHT', author: 'TOKENS', deck: 'INT'},
  {title: 'IT\'S NOT UNUSUAL', author: 'TOM JONES', deck: 'INT'},
  {title: 'SEXBOMB', author: 'TOM JONES', deck: 'INT'},
  {title: 'DANCING IN THE MOONLIGHT', author: 'TOPLOADER', deck: 'INT'},
  {title: 'AFRICA', author: 'TOTO', deck: 'INT'},
  {title: 'STRESSED OUT', author: 'TWENTY ONE PILOTS', deck: 'INT'},
  {title: 'I STILL HAVEN\'T FOUND WHAT I\'M LOOKING FOR', author: 'U2', deck: 'INT'},
  {title: 'PRIDE (IN THE NAME OF LOVE)', author: 'U2', deck: 'INT'},
  {title: 'WITH OR WITHOUT YOU', author: 'U2', deck: 'INT'},
  {title: 'WE ARE THE WORLD', author: 'USA FOR AFRICA', deck: 'INT'},
  {title: 'BROWN EYED GIRL', author: 'VAN MORRISON', deck: 'INT'},
  {title: 'CHARIOTS OF FIRE', author: 'VANGELIS', deck: 'INT'},
  {title: 'CONQUEST OF PARADISE (1492)', author: 'VANGELIS', deck: 'INT'},
  {title: 'ICE ICE BABY', author: 'VANILLA ICE', deck: 'INT'},
  {title: 'LOVE IS ALL AROUND', author: 'WET WET WET', deck: 'INT'},
  {title: 'LAST CHRISTMAS', author: 'WHAM!', deck: 'INT'},
  {title: 'WAKE ME UP BEFORE YOU GO', author: 'WHAM!', deck: 'INT'},
  {title: 'I WILL ALWAYS LOVE YOU', author: 'WHITNEY HOUSTON', deck: 'INT'},
  {title: 'SEE YOU AGAIN', author: 'WIZ KHALIFA', deck: 'INT'},
  {title: 'EINE KLEINE NACHTMUSIK', author: 'WOLFGANG A. MOZART', deck: 'INT'},
  {title: 'OWNER OF THE LONELY HEART', author: 'YES', deck: 'INT'},
  {title: 'WHAT DOES THE FOX SAY?', author: 'YLVIS', deck: 'INT'},
  {title: 'LA GRANGE', author: 'ZZ TOP', deck: 'INT'},
  {title: 'BELLA CIAO', author: '', deck: 'INT'},
  {title: 'BENNY HILL THEME', author: '', deck: 'INT'},
  {title: 'GODFATHER THEME', author: '', deck: 'INT'},
  {title: 'HARRY POTTER THEME', author: '', deck: 'INT'},
  {title: 'IMPERIAL MARCH (STAR WARS)', author: '', deck: 'INT'},
  {title: 'JAMES BOND THEME', author: '', deck: 'INT'},
  {title: 'MCDONALDS JINGLE', author: '', deck: 'INT'},
  {title: '24 BYŁ LUTEGO', author: '(SZANTA)', deck: 'POL'},
  {title: 'AMSTERDAM', author: '(SZANTA)', deck: 'POL'},
  {title: 'BITWA', author: '(SZANTA)', deck: 'POL'},
  {title: 'GDZIE TA KEJA', author: '(SZANTA)', deck: 'POL'},
  {title: 'HISZPAŃSKIE DZIEWCZYNY', author: '(SZANTA)', deck: 'POL'},
  {title: 'MARCO POLO', author: '(SZANTA)', deck: 'POL'},
  {title: 'MORSKIE OPOWIEŚCI', author: '(SZANTA)', deck: 'POL'},
  {title: 'PACYFIK', author: '(SZANTA)', deck: 'POL'},
  {title: 'POŻEGNANIE LIVERPOOLU', author: '(SZANTA)', deck: 'POL'},
  {title: 'PRESS GANG', author: '(SZANTA)', deck: 'POL'},
  {title: 'PRZECHYŁY', author: '(SZANTA)', deck: 'POL'},
  {title: 'ŚMIAŁY HARPUNNIK (NASZ DIAMENT)', author: '(SZANTA)', deck: 'POL'},
  {title: 'STARY BRYG', author: '(SZANTA)', deck: 'POL'},
  {title: 'CHODŹ, POMALUJ MÓJ ŚWIAT', author: '2 PLUS 1', deck: 'POL'},
  {title: 'PRZEZ TWE OCZY ZIELONE', author: 'AKCENT', deck: 'POL'},
  {title: 'LUBIĘ MÓWIĆ Z TOBĄ', author: 'AKURAT', deck: 'POL'},
  {title: 'CZTERDZIESTOLATEK', author: 'ANDRZEJ ROSIEWICZ', deck: 'POL'},
  {title: 'RÓŻA I BEZ (JAK ROZPĘTAŁEM IIWŚ)', author: 'ANDRZEJ ŻARNECKI', deck: 'POL'},
  {title: 'BYŁAŚ SERCA BICIEM', author: 'ANDRZEJ ZAUCHA', deck: 'POL'},
  {title: 'GUMISIE', author: 'ANDRZEJ ZAUCHA', deck: 'POL'},
  {title: 'I WSZYSTKO SIĘ MOŻE ZDARZYĆ', author: 'ANITA LIPNICKA', deck: 'POL'},
  {title: 'MOJE JEDYNE MARZENIE (PRZETAŃCZYĆ Z TOBĄ CHCĘ)', author: 'ANNA JANTAR', deck: 'POL'},
  {title: 'TYLE SŁOŃCA W CAŁYM MIEŚCIE', author: 'ANNA JANTAR', deck: 'POL'},
  {title: 'ŚWIĘTY, ŚWIĘTY UŚMIECHNIĘTY', author: 'ARKA NOEGO', deck: 'POL'},
  {title: 'PIŁEM W SPALE, SPAŁEM W PILE', author: 'ARTUR ANDRUS', deck: 'POL'},
  {title: 'SKÓRA', author: 'AYA RL', deck: 'POL'},
  {title: 'BIAŁY MIŚ', author: 'BADYLE', deck: 'POL'},
  {title: 'BIAŁA ARMIA', author: 'BAJM', deck: 'POL'},
  {title: 'MYŚLI I SŁOWA', author: 'BAJM', deck: 'POL'},
  {title: 'TA SAMA CHWILA', author: 'BAJM', deck: 'POL'},
  {title: 'FACET TO ŚWINIA', author: 'BIG CYC', deck: 'POL'},
  {title: 'MAKUMBA', author: 'BIG CYC', deck: 'POL'},
  {title: 'RUDY SIĘ ŻENI', author: 'BIG CYC', deck: 'POL'},
  {title: 'W DZIEŃ GORĄCEGO LATA', author: 'BIG DAY', deck: 'POL'},
  {title: 'DO NIEBA, DO PIEKŁA', author: 'BLUE CAFE', deck: 'POL'},
  {title: 'DAJ Z SIEBIE WSZYSTKO', author: 'BOB ONE FT. BAS TAJPAN', deck: 'POL'},
  {title: 'JESTEŚ SZALONA', author: 'BOYS', deck: 'POL'},
  {title: 'JANKO, JANECZKO', author: 'BRACIA FIGO FAGOT', deck: 'POL'},
  {title: 'WÓDA ZRYJE BANIĘ', author: 'BRACIA FIGO FAGOT', deck: 'POL'},
  {title: 'PISARZ MIŁOŚCI', author: 'BRACIA FIGO FAGOT', deck: 'POL'},
  {title: 'CZERWONE KORALE', author: 'BRATHANKI', deck: 'POL'},
  {title: 'W KINIE W LUBLINIE', author: 'BRATHANKI', deck: 'POL'},
  {title: 'KIEDY BYŁEM MAŁYM CHŁOPCEM', author: 'BREAKOUT', deck: 'POL'},
  {title: 'GRANDA', author: 'BRODKA', deck: 'POL'},
  {title: 'MIAŁ BYĆ ŚLUB', author: 'BRODKA', deck: 'POL'},
  {title: 'BAL WSZYSTKICH ŚWIĘTYCH', author: 'BUDKA SUFLERA', deck: 'POL'},
  {title: 'JOLKA, JOLKA PAMIĘTASZ', author: 'BUDKA SUFLERA', deck: 'POL'},
  {title: 'TAKIE TANGO', author: 'BUDKA SUFLERA', deck: 'POL'},
  {title: 'JEST TAKI SAMOTNY DOM', author: 'BUDKA SUFLERA', deck: 'POL'},
  {title: 'ZA OSTATNI GROSZ', author: 'BUDKA SUFLERA', deck: 'POL'},
  {title: 'KOCHAM WOLNOŚĆ', author: 'CHŁOPCY Z PLACU BRONI', deck: 'POL'},
  {title: 'LESZEK ŻUKOWSKI (NICZEGO NIE BĘDZIE ŻAL)', author: 'COMA', deck: 'POL'},
  {title: 'NOGI', author: 'CZARNO CZARNI', deck: 'POL'},
  {title: 'ANNA MARIA', author: 'CZERWONE GITARY', deck: 'POL'},
  {title: 'DOZWOLONE OD LAT OSIEMNASTU', author: 'CZERWONE GITARY', deck: 'POL'},
  {title: 'KWIATY WE WŁOSACH', author: 'CZERWONE GITARY', deck: 'POL'},
  {title: 'NIE ZADZIERAJ NOSA', author: 'CZERWONE GITARY', deck: 'POL'},
  {title: 'DZIWNY JEST TEN ŚWIAT', author: 'CZESŁAW NIEMEN', deck: 'POL'},
  {title: 'SEN O WARSZAWIE', author: 'CZESŁAW NIEMEN', deck: 'POL'},
  {title: 'MASZYNKA DO ŚWIERKANIA', author: 'CZESŁAW ŚPIEWA', deck: 'POL'},
  {title: 'MAŁOMIASTECZKOWY', author: 'DAWID PODSIADŁO', deck: 'POL'},
  {title: 'NIE MA FAL', author: 'DAWID PODSIADŁO', deck: 'POL'},
  {title: 'TRÓJKĄTY I KWADRATY', author: 'DAWID PODSIADŁO', deck: 'POL'},
  {title: 'KOCHAĆ INACZEJ', author: 'DE MONO', deck: 'POL'},
  {title: 'STATKI NA NIEBIE', author: 'DE MONO', deck: 'POL'},
  {title: 'NIE DAJ SIĘ', author: 'DODA', deck: 'POL'},
  {title: 'MY SŁOWIANIE', author: 'DONATAN CLEO', deck: 'POL'},
  {title: 'CZERWONY JAK CEGŁA', author: 'DŻEM', deck: 'POL'},
  {title: 'WEHIKUŁ CZASU', author: 'DŻEM', deck: 'POL'},
  {title: 'WHISKY', author: 'DŻEM', deck: 'POL'},
  {title: 'LIST DO M.', author: 'DŻEM', deck: 'POL'},
  {title: 'CZTEREJ PANCERNI I PIES (DESZCZE NIESPOKOJNE)', author: 'EDMUND FETTING', deck: 'POL'},
  {title: 'TO NIE JA', author: 'EDYTA GÓRNIAK', deck: 'POL'},
  {title: 'DUMKA NA DWA SERCA', author: 'EDYTA GORNIAK I MIETEK SZCZESNIAK', deck: 'POL'},
  {title: 'DZIECI', author: 'ELEKTRYCZNE GITARY', deck: 'POL'},
  {title: 'KAMIEŃ Z NAPISEM LOVE', author: 'ENEJ', deck: 'POL'},
  {title: 'JUŻ TAKI JESTEM ZIMNY DRAŃ', author: 'EUGENIUSZ BODO', deck: 'POL'},
  {title: 'UMÓWIŁEM SIĘ Z NIĄ NA DZIEWIĄTĄ', author: 'EUGENIUSZ BODO', deck: 'POL'},
  {title: 'ŻAŁUJĘ', author: 'EWELINA FLINTA', deck: 'POL'},
  {title: 'W STRONĘ SŁOŃCA', author: 'EWELINA LISOWSKA', deck: 'POL'},
  {title: 'CHCĘ TU ZOSTAĆ', author: 'FARBA', deck: 'POL'},
  {title: 'MYDŁO LUBI ZABAWĘ', author: 'FASOLKI', deck: 'POL'},
  {title: 'A GDY JEST JUŻ CIEMNO', author: 'FEEL', deck: 'POL'},
  {title: 'JAK ANIOŁA GŁOS', author: 'FEEL', deck: 'POL'},
  {title: 'LATO', author: 'FORMACJA NIEŻYWYCH SCHABUFF', deck: 'POL'},
  {title: 'KING BRUCE LEE KARATE MISTRZ', author: 'FRANEK KIMONO', deck: 'POL'},
  {title: 'ŚCIERNISCO', author: 'GOLEC UORKIESTRA', deck: 'POL'},
  {title: 'SŁODYCZE', author: 'GOLEC UORKIESTRA', deck: 'POL'},
  {title: 'NA SZCZYCIE', author: 'GRUBSON', deck: 'POL'},
  {title: 'CICHOSZA', author: 'GRZEGORZ TURNAU', deck: 'POL'},
  {title: 'NAPRAWDĘ NIE DZIEJE SIĘ NIC', author: 'GRZEGORZ TURNAU', deck: 'POL'},
  {title: 'ZANIM PÓJDĘ', author: 'HAPPYSAD', deck: 'POL'},
  {title: 'RUDY RYDZ', author: 'HELENA MAJDANIEC', deck: 'POL'},
  {title: '[SIC!]', author: 'HEY', deck: 'POL'},
  {title: 'MOJA I TWOJA NADZIEJA', author: 'HEY', deck: 'POL'},
  {title: 'A WSZYSTKO TO...', author: 'ICH TROJE', deck: 'POL'},
  {title: 'KEINE GRENZEN (ŻADNYCH GRANIC)', author: 'ICH TROJE', deck: 'POL'},
  {title: 'ZAWSZE Z TOBĄ CHCIAŁBYM BYĆ', author: 'ICH TROJE', deck: 'POL'},
  {title: 'NADZIEJA', author: 'IRA', deck: 'POL'},
  {title: 'JEJ CZARNE OCZY', author: 'IVAN I DELFIN', deck: 'POL'},
  {title: 'MURY', author: 'JACEK KACZMARSKI', deck: 'POL'},
  {title: 'NASZA KLASA', author: 'JACEK KACZMARSKI', deck: 'POL'},
  {title: 'POLICEMAN', author: 'JAMAL', deck: 'POL'},
  {title: 'BRUNETKI, BLONDYNKI', author: 'JAN KIEPURA', deck: 'POL'},
  {title: 'KOKO KOKO EURO SPOKO', author: 'JARZĘBINA', deck: 'POL'},
  {title: 'JAK ZAPOMNIEĆ', author: 'JEDEN OSIEM L', deck: 'POL'},
  {title: 'BO Z DZIEWCZYNAMI', author: 'JERZY POŁOMSKI', deck: 'POL'},
  {title: 'PAMIĘTAJCIE O OGRODACH', author: 'JONASZ KOFTA', deck: 'POL'},
  {title: 'ZA KAŻDYM RAZEM', author: 'JULA', deck: 'POL'},
  {title: 'DZIEWCZYNA SZAMANA', author: 'JUSTYNA STECZKOWSKA', deck: 'POL'},
  {title: 'MACZO', author: 'K.A.S.A.', deck: 'POL'},
  {title: 'PLUS I MINUS', author: 'KALIBER 44', deck: 'POL'},
  {title: 'EXPLOSION', author: 'KALWI & REMI', deck: 'POL'},
  {title: 'ZABIORĘ CIĘ WŁAŚNIE TAM', author: 'KANCELARIA', deck: 'POL'},
  {title: 'LEPSZY MODEL', author: 'KASIA KLICH', deck: 'POL'},
  {title: 'PROWADŹ MNIE', author: 'KASIA KOWALSKA', deck: 'POL'},
  {title: 'NIE BĄDŹ TAKI SZYBKI BILL', author: 'KASIA SOBCZYK', deck: 'POL'},
  {title: 'O MNIE SIĘ NIE MARTW', author: 'KASIA SOBCZYK', deck: 'POL'},
  {title: 'TESTOSTERON', author: 'KAYAH', deck: 'POL'},
  {title: 'PRAWY DO LEWEGO', author: 'KAYAH, BREGOVIC', deck: 'POL'},
  {title: 'BYŁAM RÓŻĄ', author: 'KAYAH, BREGOVIC', deck: 'POL'},
  {title: 'ŚPIJ, KOCHANIE ŚPIJ', author: 'KAYAH, BREGOVIC', deck: 'POL'},
  {title: '12 GROSZY', author: 'KAZIK', deck: 'POL'},
  {title: 'MÓJ BÓL JEST WIĘKSZY NIŻ TWÓJ ', author: 'KAZIK', deck: 'POL'},
  {title: 'BALLADA O JANKU WIŚNIEWSKIM', author: 'KAZIK', deck: 'POL'},
  {title: 'KOCHAM CIĘ JAK IRLANDIĘ', author: 'KOBRANOCKA', deck: 'POL'},
  {title: 'SŁODKIEGO MIŁEGO ŻYCIA', author: 'KOMBI', deck: 'POL'},
  {title: 'POKOLENIE', author: 'KOMBII', deck: 'POL'},
  {title: 'BO JESTEŚ TY', author: 'KRZYSZTOF KRAWCZYK', deck: 'POL'},
  {title: 'PAROSTATEK', author: 'KRZYSZTOF KRAWCZYK', deck: 'POL'},
  {title: 'MÓJ PRZYJACIELU', author: 'KRZYSZTOF KRAWCZYK & GORAN BREGOVIC', deck: 'POL'},
  {title: 'TRUDNO TAK', author: 'KRZYSZTOF KRAWCZYK, EDYTA BARTOSIEWICZ', deck: 'POL'},
  {title: 'KULFON CO Z CIEBIE WYROŚNIE?', author: 'KULFON I MONIKA', deck: 'POL'},
  {title: 'ARAHJA', author: 'KULT', deck: 'POL'},
  {title: 'BARANEK', author: 'KULT', deck: 'POL'},
  {title: 'BROOKLYŃSKA RADA ŻYDÓW', author: 'KULT', deck: 'POL'},
  {title: 'DO ANI', author: 'KULT', deck: 'POL'},
  {title: 'GDY NIE MA DZIECI', author: 'KULT', deck: 'POL'},
  {title: 'POLSKA', author: 'KULT', deck: 'POL'},
  {title: 'DZIŚ PÓŹNO PÓJDĘ SPAĆ', author: 'KWIAT JABŁONI', deck: 'POL'},
  {title: 'KRYZYSOWA NARZYCZONA', author: 'LADY PANK', deck: 'POL'},
  {title: 'MNIEJ NIŻ ZERO', author: 'LADY PANK', deck: 'POL'},
  {title: 'NA CO KOMU DZIŚ', author: 'LADY PANK', deck: 'POL'},
  {title: 'STACJA WARSZAWA', author: 'LADY PANK', deck: 'POL'},
  {title: 'TACY SAMI', author: 'LADY PANK', deck: 'POL'},
  {title: 'TAŃCZ GŁUPIA, TAŃCZ', author: 'LADY PANK', deck: 'POL'},
  {title: 'ZAWSZE TAM GDZIE TY', author: 'LADY PANK', deck: 'POL'},
  {title: 'JAMMIN', author: 'ŁĄKI ŁAN', deck: 'POL'},
  {title: 'HYDROPIEKŁOWSTĄPIENIE', author: 'LAO CHE', deck: 'POL'},
  {title: 'NIE RAJ', author: 'LAO CHE', deck: 'POL'},
  {title: 'WOJENKA', author: 'LAO CHE', deck: 'POL'},
  {title: 'ŻYCIE JEST JAK TRAMWAJ', author: 'LAO CHE', deck: 'POL'},
  {title: 'CHŁOPCY ', author: 'LAO CHE', deck: 'POL'},
  {title: 'ONA CZUJE WE MNIE PINIĄDZ', author: 'ŁOBUZY', deck: 'POL'},
  {title: 'PRZEŻYJ TO SAM', author: 'LOMBARD', deck: 'POL'},
  {title: 'SZKLANA POGODA', author: 'LOMBARD', deck: 'POL'},
  {title: 'AGNIESZKA', author: 'ŁZY', deck: 'POL'},
  {title: 'NARCYZ', author: 'ŁZY', deck: 'POL'},
  {title: 'OCZY SZEROKO ZAMKNIĘTE', author: 'ŁZY', deck: 'POL'},
  {title: 'CYKADY NA CYKLADACH', author: 'MAANAM', deck: 'POL'},
  {title: 'KOCHAM CIĘ KOCHANIE MOJE', author: 'MAANAM', deck: 'POL'},
  {title: 'KRAKOWSKI SPLEEN', author: 'MAANAM', deck: 'POL'},
  {title: 'SZARE MIRAŻE', author: 'MAANAM', deck: 'POL'},
  {title: 'AICHA', author: 'MAGMA', deck: 'POL'},
  {title: 'A JA WOLĘ MOJĄ MAMĘ', author: 'MAJKA JEŻOWSKA', deck: 'POL'},
  {title: 'ALIBI', author: 'MALEO REGGAE ROCKERS', deck: 'POL'},
  {title: 'BĘDZIESZ MOJĄ PANIĄ', author: 'MAREK GRECHUTA', deck: 'POL'},
  {title: 'DNI KTÓRYCH NIE ZNAMY', author: 'MAREK GRECHUTA', deck: 'POL'},
  {title: 'KOROWÓD', author: 'MAREK GRECHUTA', deck: 'POL'},
  {title: 'OCALIĆ OD ZAPOMNIENIA', author: 'MAREK GRECHUTA', deck: 'POL'},
  {title: 'ALE TO JUŻ BYŁO', author: 'MARYLA RODOWICZ', deck: 'POL'},
  {title: 'KOLOROWE JARMARKI', author: 'MARYLA RODOWICZ', deck: 'POL'},
  {title: 'MAŁGOŚKA', author: 'MARYLA RODOWICZ', deck: 'POL'},
  {title: 'NIECH ŻYJE BAL', author: 'MARYLA RODOWICZ', deck: 'POL'},
  {title: 'REMEDIUM (WSIĄŚĆ DO POCIĄGU)', author: 'MARYLA RODOWICZ', deck: 'POL'},
  {title: 'KAŻDEGO DNIA', author: 'MESAJAH', deck: 'POL'},
  {title: 'SZUKAJĄC SZCZĘŚCIA', author: 'MESAJAH FEAT. KAMIL BEDNAREK', deck: 'POL'},
  {title: 'OSTATNIA NIEDZIELA', author: 'MIECZYSŁAW FOGG', deck: 'POL'},
  {title: 'KACZUSZKA I MAK', author: 'MIECZYSŁAW WOJNICKI', deck: 'POL'},
  {title: 'MÓJ JEST TEN KAWAŁEK PODŁOGI', author: 'MR. ZOOB', deck: 'POL'},
  {title: 'JAK NIE MY TO KTO', author: 'MROZU FEAT. TOMSON', deck: 'POL'},
  {title: 'DŁUGOŚĆ DŹWIĘKU SAMOTONOŚCI', author: 'MYSLOVITZ', deck: 'POL'},
  {title: 'PEGGY BROWN', author: 'MYSLOVITZ', deck: 'POL'},
  {title: 'SCENARIUSZ DLA MOICH SĄSIADÓW', author: 'MYSLOVITZ', deck: 'POL'},
  {title: 'SPRZEDAWCY MARZEŃ', author: 'MYSLOVITZ', deck: 'POL'},
  {title: 'Z TWARZĄ MARILYN MONROE', author: 'MYSLOVITZ', deck: 'POL'},
  {title: 'KOBIETY SĄ GORĄCE', author: 'NORBI', deck: 'POL'},
  {title: 'KIEDY POWIEM SOBIE DOŚĆ (CZY WARTO)', author: 'O.N.A.', deck: 'POL'},
  {title: 'NIE PYTAJ O POLSKĘ', author: 'OBYWATEL G.C.', deck: 'POL'},
  {title: 'TAK... TAK... TO JA', author: 'OBYWATEL G.C.', deck: 'POL'},
  {title: 'JESTEM BOGIEM', author: 'PAKTOFONIKA', deck: 'POL'},
  {title: 'CAŁUJ MNIE', author: 'PAWEŁ KUKIZ & PIERSI', deck: 'POL'},
  {title: 'GŁUCHA NOC', author: 'PEJA', deck: 'POL'},
  {title: 'AUTOBIOGRAFIA', author: 'PERFECT', deck: 'POL'},
  {title: 'CHCEMY BYĆ SOBĄ', author: 'PERFECT', deck: 'POL'},
  {title: 'NIE PŁACZ EWKA', author: 'PERFECT', deck: 'POL'},
  {title: 'NIEWIELE CI MOGĘ DAĆ', author: 'PERFECT', deck: 'POL'},
  {title: 'KOŁYSANKA DLA NIEZNAJOMEJ', author: 'PERFECT', deck: 'POL'},
  {title: 'TO MY POLACY', author: 'PIĘĆ DWA', deck: 'POL'},
  {title: 'BAŁKANICA', author: 'PIERSI', deck: 'POL'},
  {title: 'NIECH MÓWIĄ, ŻE TO NIE JEST MIŁOŚĆ', author: 'PIOTR RUBIK', deck: 'POL'},
  {title: 'KOCHAĆ (TO ŁATWO POWIEDZIEĆ)', author: 'PIOTR SZCZEPANIK', deck: 'POL'},
  {title: 'POCZĄTEK', author: 'PODSIADŁO, KORTEZ, ZALEWSKI', deck: 'POL'},
  {title: 'I CIEBIE TEŻ, BARDZO', author: 'ZAWIAŁOW, PODSIADŁO, BAMBINO', deck: 'POL'},
  {title: 'GÓRNICZO HUTNICZA ORKIESTRA DĘTA', author: 'POGODNO', deck: 'POL'},
  {title: 'BYŁAŚ DLA MNIE WSZYSTKIM', author: 'POPARZENI KAWĄ TRZY', deck: 'POL'},
  {title: 'FLARY', author: 'PRO8L3M', deck: 'POL'},
  {title: 'KIEDYŚ CIĘ ZNAJDĘ', author: 'RENI JUSIS', deck: 'POL'},
  {title: 'ZAKRĘCONA', author: 'RENI JUSIS', deck: 'POL'},
  {title: 'BIAŁA FLAGA', author: 'REPUBLIKA', deck: 'POL'},
  {title: 'MAMONA', author: 'REPUBLIKA', deck: 'POL'},
  {title: 'TELEFONY', author: 'REPUBLIKA', deck: 'POL'},
  {title: 'NIE STAŁO SIĘ NIC', author: 'ROBERT GAWLIŃSKI', deck: 'POL'},
  {title: 'NA JEDNEJ Z DZIKICH PLAŹ (LUBIŁA TAŃCZYĆ)', author: 'ROTARY', deck: 'POL'},
  {title: 'JEDZIE POCIĄG Z DALEKA', author: 'RYSZARD RYNKOWSKI', deck: 'POL'},
  {title: 'ŻYCIE JEST NOWELĄ (KLAN)', author: 'RYSZARD RYNKOWSKI', deck: 'POL'},
  {title: 'NAUCZ MNIE', author: 'SARSA', deck: 'POL'},
  {title: 'OTWIERAM WINO', author: 'SIDNEY POLAK', deck: 'POL'},
  {title: 'WSZYSTKO KWITNIE WKOŁO (WIOSNA)', author: 'SKALDOWIE', deck: 'POL'},
  {title: 'WSZYSTKO MI MÓWI, ŻE MNIE KTOŚ POKOCHAŁ', author: 'SKALDOWIE', deck: 'POL'},
  {title: 'Z KOPYTA KULIG RWIE', author: 'SKALDOWIE', deck: 'POL'},
  {title: 'MIŁOŚĆ W ZAKOPANEM', author: 'SŁAWOMIR', deck: 'POL'},
  {title: 'W AUCIE', author: 'SOKÓŁ FEAT. PONO, FRED & FRANEK KIMONO', deck: 'POL'},
  {title: 'DOSKO', author: 'STACHURSKY', deck: 'POL'},
  {title: 'TYP NIEPOKORNY', author: 'STACHURSKY', deck: 'POL'},
  {title: 'CZARNY BLUES O CZWARTEJ NAD RANEM', author: 'STARE DOBRE MAŁŻEŃSTWO', deck: 'POL'},
  {title: 'Z NIM BĘDZIESZ SZCZĘŚLIWSZA ', author: 'STARE DOBRE MAŁŻEŃSTWO', deck: 'POL'},
  {title: 'CZARNY CHLEB I CZARNA KAWA', author: 'STRACHY NA LACHY', deck: 'POL'},
  {title: 'DZIEŃ DOBRY, KOCHAM CIĘ', author: 'STRACHY NA LACHY', deck: 'POL'},
  {title: 'PIŁA TANGO', author: 'STRACHY NA LACHY', deck: 'POL'},
  {title: 'RAISSA', author: 'STRACHY NA LACHY', deck: 'POL'},
  {title: 'MAŁE RZECZY', author: 'SYLWIA GRZESZCZAK', deck: 'POL'},
  {title: 'CO Z NAMI BĘDZIE', author: 'SYLWIA GRZESZCZAK & LIBER', deck: 'POL'},
  {title: 'WIEŻA RADOŚCI, WIEŻA SAMOTNOŚCI', author: 'SZTYWNY PAL AZJI', deck: 'POL'},
  {title: 'U CIOCI NA IMIENINACH', author: 'SZWAGIERKOLASKA', deck: 'POL'},
  {title: 'CHŁOPAKI NIE PŁACZĄ', author: 'T.LOVE', deck: 'POL'},
  {title: 'KING', author: 'T.LOVE', deck: 'POL'},
  {title: 'NIE NIE NIE', author: 'T.LOVE', deck: 'POL'},
  {title: 'WARSZAWA', author: 'T.LOVE', deck: 'POL'},
  {title: 'DESZCZ NA BETONIE', author: 'TACO HEMINGWAY', deck: 'POL'},
  {title: 'NASTĘPNA STACJA', author: 'TACO HEMINGWAY', deck: 'POL'},
  {title: 'TAMAGOTCHI', author: 'TACONAFIDE', deck: 'POL'},
  {title: 'ZEGARMISTRZ ŚWIATŁA', author: 'TADEUSZ WOŹNIAK', deck: 'POL'},
  {title: 'TAKIEGO JANICKA', author: 'TERAZMY', deck: 'POL'},
  {title: 'KOCHAM BYĆ Z TOBĄ', author: 'THE DUMPLINGS', deck: 'POL'},
  {title: 'DLA MNIE MASZ STAJLA', author: 'TRZECI WYMIAR', deck: 'POL'},
  {title: '10 W SKALI BEAUFORTA', author: 'TRZY KORONY', deck: 'POL'},
  {title: 'DMUCHAWCE, LATAWCE WIATR', author: 'URSZULA', deck: 'POL'},
  {title: 'KONIK NA BIEGUNACH', author: 'URSZULA', deck: 'POL'},
  {title: 'ORŁA CIEŃ', author: 'VARIUS MANX', deck: 'POL'},
  {title: 'ZANIM ZROZUMIESZ (ONA MA SIŁĘ)', author: 'VARIUS MANX', deck: 'POL'},
  {title: 'JAH JEST PREZYDENTEM', author: 'VAVAMUFFIN', deck: 'POL'},
  {title: 'ŚRODA CZWARTEK', author: 'VIDEO', deck: 'POL'},
  {title: 'WSZYSTKO JEDNO', author: 'VIDEO', deck: 'POL'},
  {title: 'BANANOWY SONG', author: 'VOX', deck: 'POL'},
  {title: 'KOLEDZY', author: 'WAGLEWSKI & MALEŃCZUK', deck: 'POL'},
  {title: 'MONIKA, DZIEWCZYNA RATOWNIKA', author: 'WAŁY JAGIELLOŃSKIE', deck: 'POL'},
  {title: 'ONA TAŃCZY DLA MNIE', author: 'WEEKEND', deck: 'POL'},
  {title: 'SZCZUPAK (IDZIE NA TARŁO)', author: 'WETLINA', deck: 'POL'},
  {title: 'BAŚKA', author: 'WILKI', deck: 'POL'},
  {title: 'BOHEMA', author: 'WILKI', deck: 'POL'},
  {title: 'SON OF THE BLUE SKY', author: 'WILKI', deck: 'POL'},
  {title: 'PRZYGODA, PRZYGODA', author: 'WIŚLANIE 69', deck: 'POL'},
  {title: 'GDZIE SIE PODZIAŁY TAMTE PRYWATKI?', author: 'WOJCIECH GĄSSOWSKI', deck: 'POL'},
  {title: 'POLONEZ Z PANA TADEUSZA', author: 'WOJCIECH KILAR', deck: 'POL'},
  {title: 'MIASTO BUDZI SIĘ', author: 'YUGOPOLIS & PAWEŁ KUKIZ', deck: 'POL'},
  {title: 'OSTATNIA NOCKA', author: 'YUGOPOLIS, MACIEJ MALEŃCZUK', deck: 'POL'},
  {title: 'MALCZIKI', author: 'YUGOTON, KAZIK', deck: 'POL'},
  {title: 'BOSO', author: 'ZAKOPOWER', deck: 'POL'},
  {title: 'CHAŁUPY WELCOME TO', author: 'ZBIGNIEW WODECKI', deck: 'POL'},
  {title: 'PSZCZÓŁKA MAJA', author: 'ZBIGNIEW WODECKI', deck: 'POL'},
  {title: 'LUBIĘ WRACAĆ TAM GDZIE BYŁEM', author: 'ZBIGNIEW WODECKI', deck: 'POL'},
  {title: 'BANIA U CYGANA', author: 'ZERO', deck: 'POL'},
  {title: 'BOB BUDOWNICZY', author: '', deck: 'POL'},
  {title: 'LIPKA (Z TAMTEJ STRONY JEZIORA)', author: '', deck: 'POL'},
  {title: 'MOTYW Z VABANK', author: '', deck: 'POL'},
  {title: 'UKRAINA (HEJ SOKOŁY)', author: '', deck: 'POL'},
  {title: 'KISS CAM (PODRYW ROKU)', author: 'MATA', deck: 'POL'},
  {title: 'SZARY ŚWIAT', author: 'SANAH, KWIAT JABŁONI', deck: 'POL'},
  {title: 'ALE JAZZ!', author: 'SANAH, VITO BAMBINO', deck: 'POL'},
  {title: 'POLONEZ Z PANA TADEUSZA', author: 'WOJCIECH KILAR', deck: 'POL'},
  {title: 'MOTYW Z REKSIA', author: '', deck: 'POL'},
  {title: 'PIOSENKA JEST DOBRA NA WSZYSTKO', author: 'KABARET STARSZYCH PANÓW ', deck: 'POL'},
  {title: 'STOKROTKA (GDZIE STRUMYK PŁYNIE Z WOLNA...)', author: '', deck: 'POL'},
  {title: 'GDZIE JEST BIAŁY WĘGORZ', author: 'CYPIS', deck: 'POL'},
  {title: 'JESTEŚMY NA WCZASACH', author: 'WOJCIECH MŁYNARSKI', deck: 'POL'},
  {title: 'SZUM', author: 'KAŚKA SOCHACKA', deck: 'POL'},
  {title: 'ŻYCIE, KOCHAM CIĘ NAD ŻYCIE ', author: 'EDYTA GEPPERT', deck: 'POL'},
]
